/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

/**
 *
 * @author Unknow
 */
public class ContactTest extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public ContactTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myBookingsPanel = new javax.swing.JPanel();
        worldAirline = new javax.swing.JLabel();
        chemseddine = new javax.swing.JLabel();
        abbas = new javax.swing.JLabel();
        td3Ing3 = new javax.swing.JLabel();
        dan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        myBookingsPanel.setBackground(new java.awt.Color(55, 112, 155));
        myBookingsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        myBookingsPanel.setLayout(null);

        worldAirline.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        worldAirline.setForeground(new java.awt.Color(255, 255, 255));
        worldAirline.setText("WorldAirline");
        myBookingsPanel.add(worldAirline);
        worldAirline.setBounds(160, 20, 230, 40);

        chemseddine.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        chemseddine.setForeground(new java.awt.Color(255, 255, 255));
        chemseddine.setText("BRAHIM KHLIL Chemseddine   :  chemseddine.brahimkhlil@edu.ece.fr ");
        myBookingsPanel.add(chemseddine);
        chemseddine.setBounds(30, 230, 510, 40);

        abbas.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 20)); // NOI18N
        abbas.setForeground(new java.awt.Color(255, 255, 255));
        abbas.setText("JIAR Abbas  :  abbas.jiar@edu.ece.fr ");
        myBookingsPanel.add(abbas);
        abbas.setBounds(30, 170, 390, 40);

        td3Ing3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 20)); // NOI18N
        td3Ing3.setForeground(new java.awt.Color(255, 255, 255));
        td3Ing3.setText("TD3 ING3");
        myBookingsPanel.add(td3Ing3);
        td3Ing3.setBounds(200, 310, 100, 40);

        dan.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 20)); // NOI18N
        dan.setForeground(new java.awt.Color(255, 255, 255));
        dan.setText("BELISSA Dan :  dan.belissa@edu.ece.fr");
        myBookingsPanel.add(dan);
        dan.setBounds(30, 110, 390, 40);

        jScrollPane1.setBackground(new java.awt.Color(255, 51, 153));

        jTable1.setBackground(new java.awt.Color(204, 0, 102));
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        myBookingsPanel.add(jScrollPane1);
        jScrollPane1.setBounds(0, 30, 452, 402);

        getContentPane().add(myBookingsPanel);
        myBookingsPanel.setBounds(0, 0, 530, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abbas;
    private javax.swing.JLabel chemseddine;
    private javax.swing.JLabel dan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel myBookingsPanel;
    private javax.swing.JLabel td3Ing3;
    private javax.swing.JLabel worldAirline;
    // End of variables declaration//GEN-END:variables
}
