/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import Exceptions.EmptyFields;
import com.toedter.calendar.JDateChooser;
import controller.*;
import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.*;
import model.*;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
//import view.PaymentPanel;

/**
 *
 * @author Chems
 */
public class testAfficherPrice extends javax.swing.JPanel {

    /**
     * Creates new form testAfficherPrice
     */
    public testAfficherPrice(ArrayList<Flight> selectedFlight, int numberOfPassengers, String className, CustomerAccount loggedInCustomer) {
        super();
        //payment = new PaymentPanel();
        this.loggedInCustomer = loggedInCustomer;
        this.flights = selectedFlight;
        this.numberOfPassengers = numberOfPassengers;
        this.className = className;
        initComponents();
        this.setVisible(true);
        this.setSize(643, 815);
        //this.setLocationRelativeTo(null);
        initComponents2();
        initComponents();
    }
    
    //Flight Details
    private javax.swing.JLabel flightDetails;
    private javax.swing.JPanel flightDetailsPanel;

    // For One Way
    private javax.swing.JLabel arrival;
    private javax.swing.JLabel arrivalAirport;
    private javax.swing.JLabel arrivalDateTime;
    private javax.swing.JLabel departure;
    private javax.swing.JLabel departureAirport;
    private javax.swing.JLabel departureDateTime;
    private javax.swing.JLabel from;
    private javax.swing.JLabel to;

    //For Round Trip
    private javax.swing.JLabel arrival2;
    private javax.swing.JLabel arrivalAirport2;
    private javax.swing.JLabel arrivalDateTime2;
    private javax.swing.JLabel departure2;
    private javax.swing.JLabel departureAirport2;
    private javax.swing.JLabel departureDateTime2;
    private javax.swing.JLabel from2;
    private javax.swing.JLabel to2;
    private JButton jButton1;

    //Passengers Details
    ArrayList<JLabel[]> labels = new ArrayList();
    ArrayList<JTextField[]> textFields = new ArrayList();
    ArrayList<JDateChooser> birthDates = new ArrayList();
    ArrayList<JComboBox<FlightSeat>> DepartAvailableSeatChoice = new ArrayList();
    ArrayList<JComboBox<FlightSeat>> ReturnAvailableSeatChoice = new ArrayList();
    private javax.swing.JScrollPane passengersScrollPane;
    private javax.swing.JPanel passengersPanel;

    //Selected flight(s)
    ArrayList<Flight> flights = new ArrayList();

    //Account Customer 
    private CustomerAccount loggedInCustomer;

    //Nber of passengers
    private final int numberOfPassengers;

    //Class selected
    private String className;

    //payement JPanel
    JPanel payment;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(643, 815));
        setMinimumSize(new java.awt.Dimension(643, 815));
        setPreferredSize(new java.awt.Dimension(643, 815));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initComponents2() {

        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
