/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author bibes
 */
public class AddCoupon extends javax.swing.JFrame {

    /**
     * Creates new form AddCoupon
     */
    public AddCoupon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        title4 = new javax.swing.JLabel();
        idflight4 = new javax.swing.JLabel();
        textidflight4 = new javax.swing.JTextField();
        idflight5 = new javax.swing.JLabel();
        textidflight5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel9.setLayout(null);

        title4.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        title4.setText("Add Coupons:");
        jPanel9.add(title4);
        title4.setBounds(380, 10, 150, 30);

        idflight4.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        idflight4.setText("Amount of the coupon:");
        jPanel9.add(idflight4);
        idflight4.setBounds(70, 180, 170, 22);

        textidflight4.setText("jTextField1");
        textidflight4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textidflight4ActionPerformed(evt);
            }
        });
        jPanel9.add(textidflight4);
        textidflight4.setBounds(260, 180, 150, 20);

        idflight5.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        idflight5.setText("Enter the code: ");
        jPanel9.add(idflight5);
        idflight5.setBounds(70, 120, 130, 22);

        textidflight5.setText("jTextField1");
        textidflight5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textidflight5ActionPerformed(evt);
            }
        });
        jPanel9.add(textidflight5);
        textidflight5.setBounds(260, 120, 150, 20);

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton2);
        jButton2.setBounds(410, 260, 73, 23);

        getContentPane().add(jPanel9);
        jPanel9.setBounds(0, 0, 960, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textidflight4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textidflight4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textidflight4ActionPerformed

    private void textidflight5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textidflight5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textidflight5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCoupon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCoupon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCoupon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCoupon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCoupon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idflight4;
    private javax.swing.JLabel idflight5;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField textidflight4;
    private javax.swing.JTextField textidflight5;
    private javax.swing.JLabel title4;
    // End of variables declaration//GEN-END:variables
}
