/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author bibes
 */
public class AddFlight extends javax.swing.JFrame {

    /**
     * Creates new form AddFlight
     */
    public AddFlight() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddaflightPanel = new javax.swing.JPanel();
        addaflight = new javax.swing.JLabel();
        nameoftheflight = new javax.swing.JLabel();
        departuredate = new javax.swing.JLabel();
        arrivaldate = new javax.swing.JLabel();
        airplane = new javax.swing.JLabel();
        pricefirst = new javax.swing.JLabel();
        numberseatsfrst = new javax.swing.JLabel();
        textpriceseatseco = new javax.swing.JTextField();
        departureairport = new javax.swing.JLabel();
        nbrseatseco = new javax.swing.JLabel();
        nbrseatsbuisness = new javax.swing.JLabel();
        arrivalairport = new javax.swing.JLabel();
        priceseateco = new javax.swing.JLabel();
        priceseatbuisness = new javax.swing.JLabel();
        textnameflight = new javax.swing.JTextField();
        textpriceseateco = new javax.swing.JTextField();
        textnbrseatsbuisness = new javax.swing.JTextField();
        textpriceseatfirst = new javax.swing.JTextField();
        textpriceseatbuisness = new javax.swing.JTextField();
        textnbrseatfirst = new javax.swing.JTextField();
        choicearrivaldate = new com.toedter.calendar.JDateChooser();
        choicedeparturedate = new com.toedter.calendar.JDateChooser();
        choiceairplane = new javax.swing.JComboBox();
        choicedepartureaiport = new javax.swing.JComboBox();
        choicearrivalairport = new javax.swing.JComboBox();
        add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddaflightPanel.setBackground(new java.awt.Color(255, 204, 204));
        AddaflightPanel.setLayout(null);

        addaflight.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        addaflight.setText("Add a flight:");
        AddaflightPanel.add(addaflight);
        addaflight.setBounds(430, 20, 140, 32);

        nameoftheflight.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        nameoftheflight.setText("Name of the flight:");
        AddaflightPanel.add(nameoftheflight);
        nameoftheflight.setBounds(50, 100, 140, 16);

        departuredate.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        departuredate.setText("Departure Date:");
        AddaflightPanel.add(departuredate);
        departuredate.setBounds(50, 150, 140, 22);

        arrivaldate.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        arrivaldate.setText("Arrival Date:");
        AddaflightPanel.add(arrivaldate);
        arrivaldate.setBounds(50, 200, 140, 22);

        airplane.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        airplane.setText("Airplane:");
        AddaflightPanel.add(airplane);
        airplane.setBounds(50, 250, 100, 22);

        pricefirst.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        pricefirst.setText("Price of a seat for this class:");
        AddaflightPanel.add(pricefirst);
        pricefirst.setBounds(525, 390, 220, 22);

        numberseatsfrst.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        numberseatsfrst.setText("Number of seats (first class):");
        AddaflightPanel.add(numberseatsfrst);
        numberseatsfrst.setBounds(525, 340, 240, 22);

        textpriceseatseco.setText("jTextField2");
        AddaflightPanel.add(textpriceseatseco);
        textpriceseatseco.setBounds(830, 100, 120, 20);

        departureairport.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        departureairport.setText("Departure Airport:");
        AddaflightPanel.add(departureairport);
        departureairport.setBounds(50, 300, 140, 22);

        nbrseatseco.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        nbrseatseco.setText("Number of seats (economic class):");
        AddaflightPanel.add(nbrseatseco);
        nbrseatseco.setBounds(525, 100, 236, 22);

        nbrseatsbuisness.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        nbrseatsbuisness.setText("Number of seats (buisness class):");
        AddaflightPanel.add(nbrseatsbuisness);
        nbrseatsbuisness.setBounds(525, 220, 240, 22);

        arrivalairport.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        arrivalairport.setText("Arrival Airport:");
        AddaflightPanel.add(arrivalairport);
        arrivalairport.setBounds(50, 350, 140, 22);

        priceseateco.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        priceseateco.setText("Price of a seat for this class:");
        AddaflightPanel.add(priceseateco);
        priceseateco.setBounds(525, 150, 210, 22);

        priceseatbuisness.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        priceseatbuisness.setText("Price of a seat for this class:");
        AddaflightPanel.add(priceseatbuisness);
        priceseatbuisness.setBounds(525, 270, 220, 22);

        textnameflight.setText("jTextField2");
        AddaflightPanel.add(textnameflight);
        textnameflight.setBounds(250, 100, 120, 20);

        textpriceseateco.setText("jTextField2");
        AddaflightPanel.add(textpriceseateco);
        textpriceseateco.setBounds(830, 150, 120, 20);

        textnbrseatsbuisness.setText("jTextField2");
        AddaflightPanel.add(textnbrseatsbuisness);
        textnbrseatsbuisness.setBounds(830, 220, 120, 20);

        textpriceseatfirst.setText("jTextField2");
        AddaflightPanel.add(textpriceseatfirst);
        textpriceseatfirst.setBounds(830, 390, 120, 20);

        textpriceseatbuisness.setText("jTextField2");
        AddaflightPanel.add(textpriceseatbuisness);
        textpriceseatbuisness.setBounds(830, 270, 120, 20);

        textnbrseatfirst.setText("jTextField2");
        AddaflightPanel.add(textnbrseatfirst);
        textnbrseatfirst.setBounds(830, 340, 120, 20);
        AddaflightPanel.add(choicearrivaldate);
        choicearrivaldate.setBounds(250, 200, 120, 20);
        AddaflightPanel.add(choicedeparturedate);
        choicedeparturedate.setBounds(250, 150, 120, 20);

        choiceairplane.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        AddaflightPanel.add(choiceairplane);
        choiceairplane.setBounds(250, 250, 120, 20);

        choicedepartureaiport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        AddaflightPanel.add(choicedepartureaiport);
        choicedepartureaiport.setBounds(250, 300, 120, 20);

        choicearrivalairport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        AddaflightPanel.add(choicearrivalairport);
        choicearrivalairport.setBounds(250, 350, 120, 20);

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        AddaflightPanel.add(add);
        add.setBounds(450, 470, 73, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddaflightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1004, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddaflightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFlight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddaflightPanel;
    private javax.swing.JButton add;
    private javax.swing.JLabel addaflight;
    private javax.swing.JLabel airplane;
    private javax.swing.JLabel arrivalairport;
    private javax.swing.JLabel arrivaldate;
    private javax.swing.JComboBox choiceairplane;
    private javax.swing.JComboBox choicearrivalairport;
    private com.toedter.calendar.JDateChooser choicearrivaldate;
    private javax.swing.JComboBox choicedepartureaiport;
    private com.toedter.calendar.JDateChooser choicedeparturedate;
    private javax.swing.JLabel departureairport;
    private javax.swing.JLabel departuredate;
    private javax.swing.JLabel nameoftheflight;
    private javax.swing.JLabel nbrseatsbuisness;
    private javax.swing.JLabel nbrseatseco;
    private javax.swing.JLabel numberseatsfrst;
    private javax.swing.JLabel pricefirst;
    private javax.swing.JLabel priceseatbuisness;
    private javax.swing.JLabel priceseateco;
    private javax.swing.JTextField textnameflight;
    private javax.swing.JTextField textnbrseatfirst;
    private javax.swing.JTextField textnbrseatsbuisness;
    private javax.swing.JTextField textpriceseatbuisness;
    private javax.swing.JTextField textpriceseateco;
    private javax.swing.JTextField textpriceseatfirst;
    private javax.swing.JTextField textpriceseatseco;
    // End of variables declaration//GEN-END:variables
}
