/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Chems
 */
public class bookingTest extends javax.swing.JPanel {

    /**
     * Creates new form bookingTest
     */
    public bookingTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        idflight2 = new javax.swing.JLabel();
        textidflight2 = new javax.swing.JTextField();
        search2 = new javax.swing.JButton();
        title2 = new javax.swing.JLabel();

        setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        add(jScrollPane3);
        jScrollPane3.setBounds(140, 140, 630, 330);

        idflight2.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        idflight2.setText("Enter the id of the booking: ");
        add(idflight2);
        idflight2.setBounds(30, 60, 200, 22);

        textidflight2.setText("jTextField1");
        textidflight2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textidflight2ActionPerformed(evt);
            }
        });
        add(textidflight2);
        textidflight2.setBounds(230, 63, 150, 20);

        search2.setText("research");
        search2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search2ActionPerformed(evt);
            }
        });
        add(search2);
        search2.setBounds(400, 60, 90, 23);

        title2.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        title2.setText("Search booking:");
        add(title2);
        title2.setBounds(370, 10, 150, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void textidflight2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textidflight2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textidflight2ActionPerformed

    private void search2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idflight2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton search2;
    private javax.swing.JTextField textidflight2;
    private javax.swing.JLabel title2;
    // End of variables declaration//GEN-END:variables
}
