/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import DataAcessObjectImpl.FlightDAOImpl;
import com.toedter.calendar.JDateChooser;
import java.util.ArrayList;
import model.*;
import controller.*;
import java.awt.event.*;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTable;

/**
 *
 * @author Unknow
 */
public class CustomerHomeFlightSearch extends javax.swing.JFrame {

    private javax.swing.JPanel DeparturePanel;
    private javax.swing.JScrollPane DepartureScrollPane;
    private javax.swing.JButton Next;
    private javax.swing.JLabel arrival;
    private com.toedter.calendar.JDateChooser arrivalDate;
    private javax.swing.JLabel backGround;
    private javax.swing.JRadioButton businessClass;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel departure;
    private javax.swing.JLabel departureAR;
    private com.toedter.calendar.JDateChooser departureDate;
    private javax.swing.JRadioButton economyClass;
    private javax.swing.JRadioButton firstClass;
    private javax.swing.JLabel from;
    private javax.swing.JComboBox<Airport> fromDeparture;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton oneWay;
    private javax.swing.JLabel passengers;
    private javax.swing.JRadioButton roundTrip;
    private javax.swing.JButton search;
    private javax.swing.JTable searchDeapartureFlights;
    private javax.swing.JLabel seat;
    private javax.swing.JComboBox<String> selectPassenger;
    private javax.swing.JLabel to;
    private javax.swing.JComboBox<Airport> toArrival;
    private javax.swing.JLabel worldWride;
    
    public CustomerHomeFlightSearch() {
        initComponents();
        this.setSize(1920,1080);
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        oneWay = new javax.swing.JRadioButton();
        economyClass = new javax.swing.JRadioButton();
        selectPassenger = new javax.swing.JComboBox<>();
        to = new javax.swing.JLabel();
        seat = new javax.swing.JLabel();
        fromDeparture = new javax.swing.JComboBox<>();
        from = new javax.swing.JLabel();
        arrivalDate = new com.toedter.calendar.JDateChooser();
        departure = new javax.swing.JLabel();
        departureDate = new com.toedter.calendar.JDateChooser();
        roundTrip = new javax.swing.JRadioButton();
        businessClass = new javax.swing.JRadioButton();
        firstClass = new javax.swing.JRadioButton();
        passengers = new javax.swing.JLabel();
        arrival = new javax.swing.JLabel();
        toArrival = new javax.swing.JComboBox<>();
        search = new javax.swing.JButton();
        worldWride = new javax.swing.JLabel();
        DeparturePanel = new javax.swing.JPanel();
        Next = new javax.swing.JButton();
        DepartureScrollPane = new javax.swing.JScrollPane();
        searchDeapartureFlights = new javax.swing.JTable();
        departureAR = new javax.swing.JLabel();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(200, 191, 191));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        buttonGroup1.add(oneWay);
        oneWay.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        oneWay.setForeground(new java.awt.Color(255, 255, 255));
        oneWay.setText("ONE-WAY");
        oneWay.setContentAreaFilled(false);
        oneWay.setFocusable(false);
        /* oneWay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneWayActionPerformed(evt);
            }
        });*/
        jPanel1.add(oneWay);
        oneWay.setBounds(190, 20, 110, 30);

        buttonGroup2.add(economyClass);
        economyClass.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        economyClass.setForeground(new java.awt.Color(255, 255, 255));
        economyClass.setText("Economy Class");
        economyClass.setContentAreaFilled(false);
        economyClass.setFocusable(false);
      /*  economyClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                economyClassActionPerformed(evt);
            }
        });*/
        jPanel1.add(economyClass);
        economyClass.setBounds(130, 380, 120, 30);

        selectPassenger.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        selectPassenger.setOpaque(false);
      /*     selectPassenger.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPassengerActionPerformed(evt);
            }
        });*/
        jPanel1.add(selectPassenger);
        selectPassenger.setBounds(130, 270, 110, 20);

        to.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        to.setIcon(new javax.swing.ImageIcon("img\\location.png")); // NOI18N
        to.setText("To");
        jPanel1.add(to);
        to.setBounds(30, 120, 70, 40);

        seat.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        seat.setIcon(new javax.swing.ImageIcon("img\\seat.png")); // NOI18N
        seat.setText("Seat");
        jPanel1.add(seat);
        seat.setBounds(30, 340, 80, 40);

        fromDeparture.setModel(new javax.swing.DefaultComboBoxModel<>(AirportController.getAllAirports()));
        fromDeparture.setOpaque(false);
        jPanel1.add(fromDeparture);
        fromDeparture.setBounds(130, 80, 110, 20);

        from.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        from.setIcon(new javax.swing.ImageIcon("img\\location.png")); // NOI18N
        from.setText("From");
        jPanel1.add(from);
        from.setBounds(30, 70, 70, 40);
        jPanel1.add(arrivalDate);
        arrivalDate.setBounds(130, 220, 110, 20);
        /*arrivalDate.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void actionPerformed(ActionEvent e ) {
                if(oneWay.isSelected()) {
                    searchDeapartureFlights.setModel(
                            new SearchFlightsTableModel(
                                    , 
                                    String arrivalAirportId, java.util.Date departureDate, int nbOfSeats, String className));
                }
                
            }
        });*/

        departure.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        departure.setIcon(new javax.swing.ImageIcon("img\\calendar.png")); // NOI18N
        departure.setText("Departure");
        jPanel1.add(departure);
        departure.setBounds(30, 170, 80, 40);
        jPanel1.add(departureDate);
        departureDate.setBounds(130, 180, 110, 20);

        buttonGroup1.add(roundTrip);
        roundTrip.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        roundTrip.setForeground(new java.awt.Color(255, 255, 255));
        roundTrip.setText("ROUND TRIP");
        roundTrip.setContentAreaFilled(false);
        roundTrip.setFocusable(false);
     /*   roundTrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundTripActionPerformed(evt);
            }
        });*/
        jPanel1.add(roundTrip);
        roundTrip.setBounds(30, 20, 110, 30);

        buttonGroup2.add(businessClass);
        businessClass.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        businessClass.setForeground(new java.awt.Color(255, 255, 255));
        businessClass.setText("Business Class");
        businessClass.setContentAreaFilled(false);
        businessClass.setFocusable(false);
     /*   businessClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                businessClassActionPerformed(evt);
            }
        });*/
        jPanel1.add(businessClass);
        businessClass.setBounds(130, 350, 110, 30);

        buttonGroup2.add(firstClass);
        firstClass.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        firstClass.setForeground(new java.awt.Color(255, 255, 255));
        firstClass.setText("First Class");
        firstClass.setContentAreaFilled(false);
        firstClass.setFocusable(false);
      /*  firstClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstClassActionPerformed(evt);
            }
        });*/
        jPanel1.add(firstClass);
        firstClass.setBounds(130, 320, 110, 30);

        passengers.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        passengers.setIcon(new javax.swing.ImageIcon("img\\users.png")); // NOI18N
        passengers.setText("Passenger(s)");
        jPanel1.add(passengers);
        passengers.setBounds(30, 260, 90, 40);

        arrival.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        arrival.setIcon(new javax.swing.ImageIcon("img\\calendar.png")); // NOI18N
        arrival.setText("Arrival");
        jPanel1.add(arrival);
        arrival.setBounds(30, 210, 80, 40);

        toArrival.setModel(new javax.swing.DefaultComboBoxModel<>(AirportController.getAllAirports()));
        toArrival.setOpaque(false);
   /*     toArrival.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toArrivalActionPerformed(evt);
            }
        });*/
        jPanel1.add(toArrival);
        toArrival.setBounds(130, 130, 110, 20);

        search.setBackground(new java.awt.Color(102, 102, 102));
        search.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search");
        search.setBorderPainted(false);
        search.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        search.setFocusable(false);
        jPanel1.add(search);
        search.setBounds(130, 440, 110, 30);
        search.setActionCommand("Search");
        search.addActionListener(new CustomerFlightSearchChoice(this));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 230, 360, 500);

        worldWride.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 110)); // NOI18N
        worldWride.setText("WorldAirline");
        getContentPane().add(worldWride);
        worldWride.setBounds(530, 10, 580, 110);

        DeparturePanel.setOpaque(false);
        DeparturePanel.setLayout(null);

        Next.setBackground(new java.awt.Color(102, 102, 102));
        Next.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        Next.setForeground(new java.awt.Color(255, 255, 255));
        Next.setText("Next");
        Next.setBorderPainted(false);
        Next.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Next.setFocusable(false);
        DeparturePanel.add(Next);
        Next.setBounds(710, 560, 110, 30);
        Next.setActionCommand("Next");

        ArrayList<Flight> flights =  new ArrayList<Flight>();
        flights.add(new FlightDAOImpl().find(5));
        flights.add(new FlightDAOImpl().find(6));
        System.out.println(flights.get(0).getIdFlight());
        SearchFlightsTableModel  model = new SearchFlightsTableModel(flights);
        searchDeapartureFlights.setFont(new java.awt.Font("Yu Gothic UI", 0, 12));
        searchDeapartureFlights.setModel(model);
        searchDeapartureFlights.setFocusable(false);
        searchDeapartureFlights.setGridColor(new java.awt.Color(0, 0, 0));
        searchDeapartureFlights.setOpaque(false);
        searchDeapartureFlights.setRowHeight(20);
        searchDeapartureFlights.setSelectionBackground(new java.awt.Color(200, 191, 191));
        searchDeapartureFlights.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        searchDeapartureFlights.setShowHorizontalLines(false);
        searchDeapartureFlights.setShowVerticalLines(false);
        searchDeapartureFlights.getTableHeader().setReorderingAllowed(false);
        DepartureScrollPane.setViewportView(searchDeapartureFlights);

        DeparturePanel.add(DepartureScrollPane);
        DepartureScrollPane.setBounds(0, 40, 800, 500);

        departureAR.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        departureAR.setForeground(new java.awt.Color(255, 255, 255));
        departureAR.setText("Departure>>");
        DeparturePanel.add(departureAR);
        departureAR.setBounds(0, 0, 150, 30);

        getContentPane().add(DeparturePanel);
        DeparturePanel.setBounds(510, 190, 820, 590);

        backGround.setIcon(new javax.swing.ImageIcon("img\\planeProgram.jpg")); // NOI18N
        getContentPane().add(backGround);
        backGround.setBounds(0, -50, 1920, 1380);

        pack();
    }

    //getters for the Search button action listener
    public Date getArrivalDate() {
        return arrivalDate.getDate();
    }

    public JRadioButton getBusinessClass() {
        return businessClass;
    }

    public Date getDepartureDate() {
        return departureDate.getDate();
    }
    
    

    public JRadioButton getEconomyClass() {
        return economyClass;
    }

    public String getFirstClass() {
        return firstClass.getText();
    }

    public JComboBox<Airport> getFromDeparture() {
        return fromDeparture;
    }

    public JRadioButton getOneWay() {
        return oneWay;
    }

    public JRadioButton getRoundTrip() {
        return roundTrip;
    }

    public int getSelectPassenger() {
        return Integer.parseInt((String) selectPassenger.getSelectedItem());
    }

    public JComboBox<Airport> getToArrival() {
        return toArrival;
    }

    public javax.swing.JTable getSearchDeapartureFlights() {
        return searchDeapartureFlights;
    }

    public void setSearchDeapartureFlightsModel(SearchFlightsTableModel searchDeapartureFlights) {
        this.searchDeapartureFlights.setModel(searchDeapartureFlights);
    }
    
    
}
