/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DataAcessObjectImpl.FlightDAOImpl;
import controller.SearchFlightsTableModel;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JPanel;
import model.Flight;

/**
 *
 * @author Unknow
 */
public class EmployeeHome extends javax.swing.JFrame {
    
    // Variables declaration - do not modify                     
    private javax.swing.JMenuItem AddCoupon;
    private javax.swing.JMenuItem AddFlight;
    private javax.swing.JMenuItem DeleteBooking;
    private javax.swing.JScrollPane DepartureScrollPane;
    private javax.swing.JMenu ManageCoupons;
    private javax.swing.JMenuItem SearchCoupon;
    private javax.swing.JMenuItem SearchFlight;
    private javax.swing.JMenuItem UpdateBooking;
    private javax.swing.JMenuItem Update_DeleteFlight;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu manageBookings;
    private javax.swing.JMenu manageFlight;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTable searchDeapartureFlights;
    // End of variables declaration     
    
    /**
     * Creates new form EmployeeHome
     */
    public EmployeeHome() {
        jPanel2 = new JPanel();
        initComponents();
        this.setVisible(true);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        System.out.println((int) screenSize.getWidth());
        System.out.println((int) screenSize.getHeight());
        this.setSize((int) screenSize.getWidth() ,(int) screenSize.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DepartureScrollPane = new javax.swing.JScrollPane();
        searchDeapartureFlights = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        manageFlight = new javax.swing.JMenu();
        SearchFlight = new javax.swing.JMenuItem();
        AddFlight = new javax.swing.JMenuItem();
        Update_DeleteFlight = new javax.swing.JMenuItem();
        manageBookings = new javax.swing.JMenu();
        UpdateBooking = new javax.swing.JMenuItem();
        DeleteBooking = new javax.swing.JMenuItem();
        ManageCoupons = new javax.swing.JMenu();
        AddCoupon = new javax.swing.JMenuItem();
        SearchCoupon = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(200, 191, 191));
        jPanel1.setLayout(null);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1100, 570);

        manageFlight.setText("Manage flights");

        SearchFlight.setText("Search Fligt");
        SearchFlight.setToolTipText("");
        SearchFlight.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getContentPane().removeAll();
                jPanel2 = new EmployeeSearchFlight();
                initComponents();
            }
        });
        manageFlight.add(SearchFlight);

        AddFlight.setText("Add Flight");
        manageFlight.add(AddFlight);

        Update_DeleteFlight.setText("Update/Delete Flight");
        Update_DeleteFlight.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });
        manageFlight.add(Update_DeleteFlight);

        menuBar.add(manageFlight);

        manageBookings.setText("Manage bookings");

        UpdateBooking.setText("SearchBooking");
        manageBookings.add(UpdateBooking);
        UpdateBooking.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getContentPane().removeAll();
                jPanel2 = new EmployeeBookingSearch();
                initComponents();
            }
        });

        DeleteBooking.setText("Update/Delete Booking");
        manageBookings.add(DeleteBooking);

        menuBar.add(manageBookings);

        ManageCoupons.setText("Manage coupons");

        AddCoupon.setText("Add Coupon");
        ManageCoupons.add(AddCoupon);

        SearchCoupon.setText("Search/Delete Coupon");
        SearchCoupon.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });
        ManageCoupons.add(SearchCoupon);

        menuBar.add(ManageCoupons);

        setJMenuBar(menuBar);
        
        jPanel1.add(jPanel2);

        pack();
    }// </editor-fold>      
    
    
                
}
