/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author bibes
 */
public class EmployeeAddCoupon extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeAddCoupon
     */
    public EmployeeAddCoupon() {
          super();
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setPreferredSize(new Dimension((int)screenSize.getWidth(),(int)screenSize.getHeight()));
        setBounds(0, 0, 1100, 570);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        textidflight4 = new javax.swing.JTextField();
        idflight4 = new javax.swing.JLabel();
        idflight5 = new javax.swing.JLabel();
        textidflight5 = new javax.swing.JTextField();
        title4 = new javax.swing.JLabel();

        setLayout(null);

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
          
            }
        });
        add(jButton2);
        jButton2.setBounds(410, 260, 73, 23);

        textidflight4.setText("jTextField1");
        textidflight4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            
            }
        });
        add(textidflight4);
        textidflight4.setBounds(260, 180, 150, 20);

        idflight4.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        idflight4.setText("Amount of the coupon:");
        add(idflight4);
        idflight4.setBounds(70, 180, 170, 22);

        idflight5.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        idflight5.setText("Enter the code: ");
        add(idflight5);
        idflight5.setBounds(70, 120, 130, 22);

        textidflight5.setText("jTextField1");
        textidflight5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
        
            }
        });
        add(textidflight5);
        textidflight5.setBounds(260, 120, 150, 20);

        title4.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        title4.setText("Add Coupons:");
        add(title4);
        title4.setBounds(380, 10, 150, 30);
    }// </editor-fold>                        



    // Variables declaration - do not modify                     
    private javax.swing.JLabel idflight4;
    private javax.swing.JLabel idflight5;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField textidflight4;
    private javax.swing.JTextField textidflight5;
    private javax.swing.JLabel title4;
    // End of variables declaration                   
}
