/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author bibes
 */
public class EmployeeUpdateDeleteFlight extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeUpdateDeleteFlight
     */
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton addseat;
    private javax.swing.JLabel airplane1;
    private javax.swing.JLabel arrivalairport1;
    private javax.swing.JLabel arrivaldate1;
    private javax.swing.JComboBox choiceairplane1;
    private javax.swing.JComboBox choicearrivalairport1;
    private com.toedter.calendar.JDateChooser choicearrivaldate1;
    private javax.swing.JComboBox choicedepartureaiport1;
    private com.toedter.calendar.JDateChooser choicedeparturedate1;
    private javax.swing.JButton delete;
    private javax.swing.JButton deleteseat1;
    private javax.swing.JLabel deparrturedate1;
    private javax.swing.JLabel departureairport1;
    private javax.swing.JLabel idflight;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameflight;
    private javax.swing.JButton search;
    private javax.swing.JTable tableseat;
    private javax.swing.JTextField textidflight;
    private javax.swing.JTextField textnameflight1;
    private javax.swing.JLabel title;
    private javax.swing.JButton update;
    // End of variables declaration    
    
    
    public EmployeeUpdateDeleteFlight() {
        super();
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setPreferredSize(new Dimension((int)screenSize.getWidth(),(int)screenSize.getHeight()));
        setBounds(0, 0, 1100, 570);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        title = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        textidflight = new javax.swing.JTextField();
        idflight = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        deparrturedate1 = new javax.swing.JLabel();
        arrivaldate1 = new javax.swing.JLabel();
        arrivalairport1 = new javax.swing.JLabel();
        departureairport1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableseat = new javax.swing.JTable();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        deleteseat1 = new javax.swing.JButton();
        addseat = new javax.swing.JButton();
        choicearrivaldate1 = new com.toedter.calendar.JDateChooser();
        choicedeparturedate1 = new com.toedter.calendar.JDateChooser();
        choicedepartureaiport1 = new javax.swing.JComboBox();
        choicearrivalairport1 = new javax.swing.JComboBox();
        airplane1 = new javax.swing.JLabel();
        choiceairplane1 = new javax.swing.JComboBox();
        textnameflight1 = new javax.swing.JTextField();
        nameflight = new javax.swing.JLabel();

        setLayout(null);

        title.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        title.setText("Search Flight:");
        add(title);
        title.setBounds(370, 10, 110, 30);

        search.setText("research");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               
            }
        });
        add(search);
        search.setBounds(400, 60, 90, 23);

        textidflight.setText("jTextField1");
        textidflight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
           
            }
        });
        add(textidflight);
        textidflight.setBounds(220, 63, 150, 20);

        idflight.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        idflight.setText("Enter the id of a flight: ");
        add(idflight);
        idflight.setBounds(40, 60, 156, 22);

        jPanel3.setBackground(new java.awt.Color(0, 60, 200));
        jPanel3.setLayout(null);

        deparrturedate1.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        deparrturedate1.setText("Departure Date:");
        jPanel3.add(deparrturedate1);
        deparrturedate1.setBounds(40, 30, 130, 22);

        arrivaldate1.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        arrivaldate1.setText("Arrival Date:");
        jPanel3.add(arrivaldate1);
        arrivaldate1.setBounds(40, 70, 120, 22);

        arrivalairport1.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        arrivalairport1.setText("Arrival Airport:");
        jPanel3.add(arrivalairport1);
        arrivalairport1.setBounds(40, 150, 130, 22);

        departureairport1.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        departureairport1.setText("Departure Airport:");
        jPanel3.add(departureairport1);
        departureairport1.setBounds(40, 110, 140, 22);

        tableseat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tableseat);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(330, 30, 440, 180);

        update.setText("update");
        jPanel3.add(update);
        update.setBounds(410, 230, 67, 23);

        delete.setText("Delete");
        jPanel3.add(delete);
        delete.setBounds(610, 230, 63, 23);

        deleteseat1.setText("delete seat");
        jPanel3.add(deleteseat1);
        deleteseat1.setBounds(800, 60, 90, 23);

        addseat.setText("add seat");
        jPanel3.add(addseat);
        addseat.setBounds(800, 150, 90, 23);
        jPanel3.add(choicearrivaldate1);
        choicearrivaldate1.setBounds(190, 70, 120, 20);
        jPanel3.add(choicedeparturedate1);
        choicedeparturedate1.setBounds(190, 30, 120, 20);

        choicedepartureaiport1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        choicedepartureaiport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
              
            }
        });
        jPanel3.add(choicedepartureaiport1);
        choicedepartureaiport1.setBounds(190, 110, 120, 20);

        choicearrivalairport1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(choicearrivalairport1);
        choicearrivalairport1.setBounds(190, 150, 120, 20);

        airplane1.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        airplane1.setText("Airplane:");
        jPanel3.add(airplane1);
        airplane1.setBounds(40, 230, 100, 22);

        choiceairplane1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(choiceairplane1);
        choiceairplane1.setBounds(190, 230, 120, 20);

        textnameflight1.setText("jTextField2");
        jPanel3.add(textnameflight1);
        textnameflight1.setBounds(190, 190, 120, 20);

        nameflight.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        nameflight.setText("Name of the flight:");
        jPanel3.add(nameflight);
        nameflight.setBounds(40, 190, 140, 22);

        add(jPanel3);
        jPanel3.setBounds(30, 110, 930, 320);
    }// </editor-fold>                        

   

                   
}
