/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AirplaneController;
import controller.AirportController;
import controller.FlightController;
import controller.FlightSeatsController;
import controller.SearchFlightSeatsTableModel;
import controller.SearchFlightsTableModel;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import model.Airplane;
import model.Airport;
import model.Flight;
import model.FlightSeat;

/**
 *
 * @author bibes
 */
public class EmployeeUpdateDeleteFlight extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeUpdateDeleteFlight
     */
    public EmployeeUpdateDeleteFlight() {
       super();
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setPreferredSize(new Dimension((int)screenSize.getWidth(),(int)screenSize.getHeight()));
        setBounds(0, 0, 1100, 570);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        title = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        textidflight = new javax.swing.JTextField();
        idflight = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        deparrturedate1 = new javax.swing.JLabel();
        arrivaldate1 = new javax.swing.JLabel();
        arrivalairport1 = new javax.swing.JLabel();
        departureairport1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableseat = new javax.swing.JTable();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        deleteseat1 = new javax.swing.JButton();
        addseat = new javax.swing.JButton();
        choicearrivaldate1 = new com.toedter.calendar.JDateChooser();
        choicedeparturedate1 = new com.toedter.calendar.JDateChooser();
        choicedepartureaiport1 = new javax.swing.JComboBox();
        choicearrivalairport1 = new javax.swing.JComboBox();
        airplane1 = new javax.swing.JLabel();
        choiceairplane1 = new javax.swing.JComboBox();
        textnameflight1 = new javax.swing.JTextField();
        nameflight = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        final Airport[] tab=AirportController.getAllAirports();
        final Airplane[] tab1=AirplaneController.getAllAirports();
        

        setLayout(null);

        title.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        title.setText("Search Flight:");
        add(title);
        title.setBounds(370, 10, 110, 30);

        search.setText("research");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (!textidflight.getText().isEmpty())
                {
                    ArrayList<Flight> flight= new ArrayList();
                    
                    flight.add(FlightController.getFlight(Integer.parseInt(textidflight.getText())));
                    
                    choicedeparturedate1.setDate(FlightController.getFlight(Integer.parseInt(textidflight.getText())).getDepartureDate());
                    choicearrivaldate1.setDate(FlightController.getFlight(Integer.parseInt(textidflight.getText())).getArrivalDate());
                    textnameflight1.setText(FlightController.getFlight(Integer.parseInt(textidflight.getText())).getAirlineName());
                    jComboBox3.setSelectedItem(FlightController.getFlight(Integer.parseInt(textidflight.getText())).getDepartureHourTimeToString());
                    jComboBox1.setSelectedItem(FlightController.getFlight(Integer.parseInt(textidflight.getText())).getDepartureMinTimeToString());
                    jComboBox4.setSelectedItem(FlightController.getFlight(Integer.parseInt(textidflight.getText())).getArrivalHourTimeToString());
                    jComboBox2.setSelectedItem(FlightController.getFlight(Integer.parseInt(textidflight.getText())).getArrivalMinTimeToString());
                    
                    
                    for(int i=0;i<tab.length; i++)
                    {
                        if (tab[i].getNameAirport().equals(FlightController.getFlight(Integer.parseInt(textidflight.getText())).getDepartureAirport().getNameAirport()))
                        {
                            choicedepartureaiport1.setSelectedIndex(i);
                        }
                        if (tab[i].getNameAirport().equals(FlightController.getFlight(Integer.parseInt(textidflight.getText())).getArrivalAirport().getNameAirport()))
                        {
                            choicearrivalairport1.setSelectedIndex(i);
                        }
                    }
                    
                    for (int j=0;j<tab1.length;j++)
                    {
                        if (tab1[j].getModel().equals(FlightController.getFlight(Integer.parseInt(textidflight.getText())).getAirplane().getModel()))
                        {
                            choiceairplane1.setSelectedIndex(j);
                        }
                    }
                    ArrayList<FlightSeat> flightSeats=new ArrayList();
                    flightSeats= FlightSeatsController.getFlightSeats(Integer.parseInt(textidflight.getText()));
                    SearchFlightSeatsTableModel model=new SearchFlightSeatsTableModel(flightSeats);
                    tableseat.setModel(model);
                    
                }
             
            }
        });
        add(search);
        search.setBounds(400, 60, 90, 23);

        textidflight.setText("");
        add(textidflight);
        textidflight.setBounds(220, 63, 150, 20);

        idflight.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        idflight.setText("Enter the id of a flight: ");
        add(idflight);
        idflight.setBounds(40, 60, 156, 22);

        jPanel3.setBackground(new java.awt.Color(0, 60, 200));
        jPanel3.setLayout(null);

        deparrturedate1.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        deparrturedate1.setText("Departure Date:");
        jPanel3.add(deparrturedate1);
        deparrturedate1.setBounds(40, 30, 130, 22);

        arrivaldate1.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        arrivaldate1.setText("Arrival Date:");
        jPanel3.add(arrivaldate1);
        arrivaldate1.setBounds(40, 70, 120, 22);

        arrivalairport1.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        arrivalairport1.setText("Arrival Airport:");
        jPanel3.add(arrivalairport1);
        arrivalairport1.setBounds(40, 150, 130, 22);

        departureairport1.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        departureairport1.setText("Departure Airport:");
        jPanel3.add(departureairport1);
        departureairport1.setBounds(40, 110, 140, 22);

        
        jScrollPane1.setViewportView(tableseat);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(440, 30, 440, 180);

        update.setText("update Flight");
        jPanel3.add(update);
        update.setBounds(540, 240, 100, 20);
        update.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
                 Timestamp dateDeparture=new Timestamp(choicedeparturedate1.getDate().getYear(),choicedeparturedate1.getDate().getMonth(),
                        choicedeparturedate1.getDate().getDay(),Integer.parseInt(jComboBox3.getSelectedItem().toString()),Integer.parseInt(jComboBox1.getSelectedItem().toString()),0,0);
                 
                   Timestamp dateArrival=new Timestamp(choicearrivaldate1.getDate().getYear(),choicearrivaldate1.getDate().getMonth(),
                        choicearrivaldate1.getDate().getDay(),Integer.parseInt(jComboBox4.getSelectedItem().toString()),Integer.parseInt(jComboBox2.getSelectedItem().toString()),0,0);
                 
                FlightController.updateFlight(Integer.parseInt(textidflight.getText()),((Airplane) choiceairplane1.getSelectedItem()).getIdAirplane() , textnameflight1.getText(),
                        ((Airport)choicedepartureaiport1.getSelectedItem()).getIdAirport() , ((Airport)choicearrivalairport1.getSelectedItem()).getIdAirport(), dateDeparture, dateArrival);
           
            }
        });

        delete.setText("Delete");
        jPanel3.add(delete);
        delete.setBounds(730, 240, 63, 23);
        delete.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
                Timestamp dateDeparture=new Timestamp(choicedeparturedate1.getDate().getYear(),choicedeparturedate1.getDate().getMonth(),
                        choicedeparturedate1.getDate().getDay(),Integer.parseInt(jComboBox3.getSelectedItem().toString()),Integer.parseInt(jComboBox1.getSelectedItem().toString()),0,0);
                 
                   Timestamp dateArrival=new Timestamp(choicearrivaldate1.getDate().getYear(),choicearrivaldate1.getDate().getMonth(),
                        choicearrivaldate1.getDate().getDay(),Integer.parseInt(jComboBox4.getSelectedItem().toString()),Integer.parseInt(jComboBox2.getSelectedItem().toString()),0,0);
                
                
                
                
                
                
                
                
            }
        });

        deleteseat1.setText("delete seat");
        jPanel3.add(deleteseat1);
        deleteseat1.setBounds(900, 50, 90, 23);
        deleteseat1.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (!tableseat.getSelectionModel().isSelectionEmpty())  //If we select a flight
                {
                    
                    
                    String stringSeatNumber = tableseat.getValueAt(tableseat.getSelectedRow(), 0).toString();
                    int seatNumber = Integer.parseInt(stringSeatNumber); 
                    
                    String className = tableseat.getValueAt(tableseat.getSelectedRow(), 1).toString();
                    String stringseatPrice = tableseat.getValueAt(tableseat.getSelectedRow(), 2).toString();
                    BigDecimal seatPrice=new BigDecimal(stringseatPrice);
                    
                    boolean isAvailable;
                    String stringIsAvailable = tableseat.getValueAt(tableseat.getSelectedRow(), 3).toString();
                        if(stringIsAvailable.equals("Yes"))
                        {
                            isAvailable=true;
                        }
                        else
                        {
                            isAvailable=false;
                        }
                        
                        FlightSeat flightSeat= new FlightSeat(seatNumber,className,seatPrice,isAvailable);
                        FlightSeatsController.deleteFlightSeat(flightSeat);
                    
                    
                }
                
            }
        });

        addseat.setText("add seat");
        jPanel3.add(addseat);
        addseat.setBounds(900, 160, 90, 23);
        addseat.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (!textidflight.getText().isEmpty())
                {
                    new EmployeeAddSeat(Integer.parseInt(textidflight.getText()));
                    

                }
                
            }
        });
        
        
        jPanel3.add(choicearrivaldate1);
        choicearrivaldate1.setBounds(190, 70, 120, 20);
        jPanel3.add(choicedeparturedate1);
        choicedeparturedate1.setBounds(190, 30, 120, 20);
        

        
        choicedepartureaiport1.setModel(new DefaultComboBoxModel(tab));
        jPanel3.add(choicedepartureaiport1);
        choicedepartureaiport1.setBounds(190, 110, 120, 20);

        choicearrivalairport1.setModel(new DefaultComboBoxModel(tab));
        jPanel3.add(choicearrivalairport1);
        choicearrivalairport1.setBounds(190, 150, 120, 20);

        airplane1.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        airplane1.setText("Airplane:");
        jPanel3.add(airplane1);
        airplane1.setBounds(40, 230, 100, 22);

        choiceairplane1.setModel(new DefaultComboBoxModel(tab1));
        jPanel3.add(choiceairplane1);
        choiceairplane1.setBounds(190, 230, 120, 20);

        textnameflight1.setText("");
        jPanel3.add(textnameflight1);
        textnameflight1.setBounds(190, 190, 120, 20);

        nameflight.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        nameflight.setText("Name of the flight:");
        jPanel3.add(nameflight);
        nameflight.setBounds(40, 190, 140, 22);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20","21", "22", "23", "24" }));
        jPanel3.add(jComboBox3);
        jComboBox3.setBounds(320, 30, 40, 20);

        jLabel2.setText("H");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(370, 30, 10, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20","21", "22", "23", "24", "25", "26", "27", "28", "29", "30","31", "32", "33", "34", "35", "36", "37", "38", "39", "40","41", "42", "43", "44", "45", "46", "47", "48", "49", "50","51", "52", "53", "54", "55", "56", "57", "58", "59", "60"  }));
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(390, 30, 40, 20);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20","21", "22", "23", "24" }));
        jPanel3.add(jComboBox4);
        jComboBox4.setBounds(320, 70, 40, 20);

        jLabel3.setText("H");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(370, 70, 10, 14);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20","21", "22", "23", "24", "25", "26", "27", "28", "29", "30","31", "32", "33", "34", "35", "36", "37", "38", "39", "40","41", "42", "43", "44", "45", "46", "47", "48", "49", "50","51", "52", "53", "54", "55", "56", "57", "58", "59", "60"  }));
        jPanel3.add(jComboBox2);
        jComboBox2.setBounds(390, 70, 40, 20);

        add(jPanel3);
        jPanel3.setBounds(30, 110, 1020, 340);
    }// </editor-fold>                        

 

    // Variables declaration - do not modify                     
    private javax.swing.JButton addseat;
    private javax.swing.JLabel airplane1;
    private javax.swing.JLabel arrivalairport1;
    private javax.swing.JLabel arrivaldate1;
    private javax.swing.JComboBox choiceairplane1;
    private javax.swing.JComboBox choicearrivalairport1;
    private com.toedter.calendar.JDateChooser choicearrivaldate1;
    private javax.swing.JComboBox choicedepartureaiport1;
    private com.toedter.calendar.JDateChooser choicedeparturedate1;
    private javax.swing.JButton delete;
    private javax.swing.JButton deleteseat1;
    private javax.swing.JLabel deparrturedate1;
    private javax.swing.JLabel departureairport1;
    private javax.swing.JLabel idflight;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameflight;
    private javax.swing.JButton search;
    private javax.swing.JTable tableseat;
    private javax.swing.JTextField textidflight;
    private javax.swing.JTextField textnameflight1;
    private javax.swing.JLabel title;
    private javax.swing.JButton update;
    
    // End of variables declaration                   
}
