/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DataAcessObjectImpl.BookingDAOImpl;
import controller.BookingController;
import controller.SearchTicketsTableModel;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Date;
import model.Booking;

/**
 *
 * @author bibes
 */
public class EmployeeUpdateDeleteBooking extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeUpdateDeleteBooking
     */
    public EmployeeUpdateDeleteBooking() {
         super();
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setPreferredSize(new Dimension((int)screenSize.getWidth(),(int)screenSize.getHeight()));
        setBounds(0, 0, 1100, 570);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        title1 = new javax.swing.JLabel();
        search1 = new javax.swing.JButton();
        textidflight1 = new javax.swing.JTextField();
        idflight1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        deparrturedate2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableseat1 = new javax.swing.JTable();
        update1 = new javax.swing.JButton();
        delete1 = new javax.swing.JButton();
        deletetickets = new javax.swing.JButton();
        choicedeparturedate2 = new com.toedter.calendar.JDateChooser();
        priceofaseat2 = new javax.swing.JTextField();
        priceofaseat3 = new javax.swing.JLabel();
        priceofaseat4 = new javax.swing.JLabel();
        priceofaseat5 = new javax.swing.JTextField();
        deletetickets1 = new javax.swing.JButton();

        setLayout(null);

        title1.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        title1.setText("Search booking:");
        add(title1);
        title1.setBounds(370, 10, 150, 30);

        search1.setText("research");
        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (!textidflight1.getText().isEmpty())
                {
                    BookingController.getBooking(Integer.parseInt(textidflight1.getText()));
                    choicedeparturedate2.setDate(BookingController.getBooking(Integer.parseInt(textidflight1.getText())).getBookingDate());
                    tableseat1.setModel(new SearchTicketsTableModel(Integer.parseInt(textidflight1.getText())));
                    
                }
                
            }
        });
        add(search1);
        search1.setBounds(400, 60, 90, 23);

        textidflight1.setText("");
        textidflight1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            
            }
        });
        add(textidflight1);
        textidflight1.setBounds(230, 63, 150, 20);

        idflight1.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        idflight1.setText("Enter the id of the booking: ");
        add(idflight1);
        idflight1.setBounds(30, 60, 200, 22);

        jPanel6.setBackground(new java.awt.Color(240, 240, 0));
        jPanel6.setLayout(null);

        deparrturedate2.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        deparrturedate2.setText("Date of the booking:");
        jPanel6.add(deparrturedate2);
        deparrturedate2.setBounds(40, 40, 150, 22);

        tableseat1.setModel(new SearchTicketsTableModel());
        jScrollPane2.setViewportView(tableseat1);

        jPanel6.add(jScrollPane2);
        jScrollPane2.setBounds(330, 30, 440, 180);

        update1.setText("update");
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingController.updateBooking(Integer.parseInt(textidflight1.getText()), (Date) choicedeparturedate2.getDate(), Integer.parseInt(priceofaseat5.getText()), Integer.parseInt(priceofaseat2.getText()), Integer.parseInt(textidflight1.getText()));
              
            }
        });
        jPanel6.add(update1);
        update1.setBounds(40, 200, 67, 23);

        delete1.setText("Delete");
        jPanel6.add(delete1);
        delete1.setBounds(210, 200, 63, 23);

        deletetickets.setText("Delete ticket");
        deletetickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
              
            }
        });
        jPanel6.add(deletetickets);
        deletetickets.setBounds(780, 130, 110, 23);
        jPanel6.add(choicedeparturedate2);
        choicedeparturedate2.setBounds(190, 40, 120, 20);

        priceofaseat2.setText("");
        priceofaseat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
     
            }
        });
        jPanel6.add(priceofaseat2);
        priceofaseat2.setBounds(190, 130, 120, 20);

        priceofaseat3.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        priceofaseat3.setText("Coupon:");
        jPanel6.add(priceofaseat3);
        priceofaseat3.setBounds(40, 120, 140, 30);

        priceofaseat4.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        priceofaseat4.setText("Customer account:");
        jPanel6.add(priceofaseat4);
        priceofaseat4.setBounds(40, 80, 140, 30);

        priceofaseat5.setText("");
        jPanel6.add(priceofaseat5);
        priceofaseat5.setBounds(190, 90, 120, 20);

        deletetickets1.setText("Update ticket");
        deletetickets1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });
        jPanel6.add(deletetickets1);
        deletetickets1.setBounds(780, 80, 110, 23);

        add(jPanel6);
        jPanel6.setBounds(70, 140, 920, 280);
    }// </editor-fold>                        

                                      


    // Variables declaration - do not modify                     
    private com.toedter.calendar.JDateChooser choicedeparturedate2;
    private javax.swing.JButton delete1;
    private javax.swing.JButton deletetickets;
    private javax.swing.JButton deletetickets1;
    private javax.swing.JLabel deparrturedate2;
    private javax.swing.JLabel idflight1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField priceofaseat2;
    private javax.swing.JLabel priceofaseat3;
    private javax.swing.JLabel priceofaseat4;
    private javax.swing.JTextField priceofaseat5;
    private javax.swing.JButton search1;
    private javax.swing.JTable tableseat1;
    private javax.swing.JTextField textidflight1;
    private javax.swing.JLabel title1;
    private javax.swing.JButton update1;
    // End of variables declaration                   
}
