/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DataAcessObjectImpl.FlightDAOImpl;
import controller.SearchFlightsTableModel;
import java.util.ArrayList;
import model.Flight;

/**
 *
 * @author Chems
 */
public class EmployeeSearchTest extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeSearchTest
     */
    public EmployeeSearchTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        title1 = new javax.swing.JLabel();
        search1 = new javax.swing.JButton();
        textidflight1 = new javax.swing.JTextField();
        idflight1 = new javax.swing.JLabel();
        DepartureScrollPane1 = new javax.swing.JScrollPane();
        searchDeapartureFlights1 = new javax.swing.JTable();

        jPanel2.setLayout(null);

        title1.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        title1.setText("Search Flight:");
        jPanel2.add(title1);
        title1.setBounds(370, 10, 110, 30);

        search1.setText("research");
        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1ActionPerformed(evt);
            }
        });
        jPanel2.add(search1);
        search1.setBounds(400, 60, 90, 23);

        textidflight1.setText("jTextField1");
        textidflight1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textidflight1ActionPerformed(evt);
            }
        });
        jPanel2.add(textidflight1);
        textidflight1.setBounds(220, 63, 150, 20);

        idflight1.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        idflight1.setText("Enter the id of a flight: ");
        jPanel2.add(idflight1);
        idflight1.setBounds(40, 60, 156, 22);

        ArrayList<Flight> flights =  new ArrayList<Flight>();
        flights.add(new FlightDAOImpl().find(5));
        System.out.println(flights.get(0).getIdFlight());
        SearchFlightsTableModel  model = new SearchFlightsTableModel(flights);
        searchDeapartureFlights1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12));
        searchDeapartureFlights1.setModel(model);
        searchDeapartureFlights1.setFocusable(false);
        searchDeapartureFlights1.setGridColor(new java.awt.Color(0, 0, 0));
        searchDeapartureFlights1.setOpaque(false);
        searchDeapartureFlights1.setRowHeight(20);
        searchDeapartureFlights1.setSelectionBackground(new java.awt.Color(200, 191, 191));
        searchDeapartureFlights1.setShowHorizontalLines(false);
        searchDeapartureFlights1.setShowVerticalLines(false);
        searchDeapartureFlights1.getTableHeader().setReorderingAllowed(false);
        DepartureScrollPane1.setViewportView(searchDeapartureFlights1);

        jPanel2.add(DepartureScrollPane1);
        DepartureScrollPane1.setBounds(210, 140, 452, 402);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search1ActionPerformed

    private void textidflight1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textidflight1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textidflight1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane DepartureScrollPane1;
    private javax.swing.JLabel idflight1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton search1;
    private javax.swing.JTable searchDeapartureFlights1;
    private javax.swing.JTextField textidflight1;
    private javax.swing.JLabel title1;
    // End of variables declaration//GEN-END:variables
}
