/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.FlightSeatsController;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import model.FlightSeat;

/**
 *
 * @author bibes
 */
public class EmployeeAddSeat extends javax.swing.JFrame {
    
        // Variables declaration - do not modify                     
   private javax.swing.JComboBox availabilty;
    private javax.swing.JComboBox className;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField seatNumber;
    // End of variables declaration     

    /**
     * Creates new form EmployeeAddSeat
     */
    public EmployeeAddSeat(int idFlight) {
        initComponents(idFlight);
        setVisible(true);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(final int idFlight) {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
         availabilty = new javax.swing.JComboBox();
        seatNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        className = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(55, 112, 155));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Availability:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 210, 90, 40);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add a Seat");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 10, 100, 40);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Seat Number:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 90, 90, 40);

        availabilty.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes", "No"}));
        jPanel1.add(availabilty);
        availabilty.setBounds(130, 220, 100, 20);
        jPanel1.add(seatNumber);
        seatNumber.setBounds(130, 100, 100, 20);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Class Name:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 130, 90, 40);

        className.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Economy Class", "Buisness Class", "First Class"}));
        jPanel1.add(className);
        className.setBounds(130, 140, 100, 20);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Seat Price:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 170, 90, 40);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
          
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(130, 180, 100, 20);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (!((seatNumber.getText().isEmpty())&&(jTextField4.getText().isEmpty())))
                {
                    if (FlightSeatsController.CheckFlightSeatInfo(seatNumber.getText(), jTextField4.getText()))
                    {
                        boolean isAvailable;
                        if(availabilty.getSelectedItem().toString().equals("Yes"))
                        {
                            isAvailable=true;
                        }
                        else
                        {
                            isAvailable=false;
                        }
                        
                        FlightSeat seat=new FlightSeat(Integer.parseInt(seatNumber.getText()),className.getSelectedItem().toString(),new BigDecimal(jTextField4.getText()),isAvailable);
                        FlightSeatsController.addFlightSeat(seat,idFlight);
                        
                    }
                }
                
                
   
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 280, 83, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

                                     

  

              
}
