/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AirplaneController;
import controller.AirportController;
import controller.FlightController;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import model.Airplane;
import model.Airport;

/**
 *
 * @author bibes
 */
public class EmployeeAddFlight extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeAddFlight
     * 
     */
    public EmployeeAddFlight() {
        super();
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setPreferredSize(new Dimension((int)screenSize.getWidth(),(int)screenSize.getHeight()));
        setBounds(0, 0, 1100, 570);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        textpriceseatseco = new javax.swing.JTextField();
        addaflight = new javax.swing.JLabel();
        nbrseatseco = new javax.swing.JLabel();
        priceseateco = new javax.swing.JLabel();
        textpriceseateco = new javax.swing.JTextField();
        textnbrseatsbuisness = new javax.swing.JTextField();
        textpriceseatbuisness = new javax.swing.JTextField();
        nbrseatsbuisness = new javax.swing.JLabel();
        priceseatbuisness = new javax.swing.JLabel();
        numberseatsfrst = new javax.swing.JLabel();
        pricefirst = new javax.swing.JLabel();
        textpriceseatfirst = new javax.swing.JTextField();
        textnbrseatfirst = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        choicearrivalairport = new javax.swing.JComboBox();
        arrivalairport = new javax.swing.JLabel();
        departureairport = new javax.swing.JLabel();
        choicedepartureaiport = new javax.swing.JComboBox();
        choiceairplane = new javax.swing.JComboBox();
        airplane = new javax.swing.JLabel();
        arrivaldate = new javax.swing.JLabel();
        choicearrivaldate = new com.toedter.calendar.JDateChooser();
        choicedeparturedate = new com.toedter.calendar.JDateChooser();
        departuredate = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(null);

        textpriceseatseco.setText("jTextField2");
        add(textpriceseatseco);
        textpriceseatseco.setBounds(830, 100, 120, 20);

        setBackground(new java.awt.Color(55, 112, 155));
        addaflight.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        addaflight.setText("Add a flight:");
        add(addaflight);
        addaflight.setBounds(430, 20, 140, 32);

        nbrseatseco.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        nbrseatseco.setText("Number of seats (economic class):");
        add(nbrseatseco);
        nbrseatseco.setBounds(525, 100, 236, 22);

        priceseateco.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        priceseateco.setText("Price of a seat for this class:");
        add(priceseateco);
        priceseateco.setBounds(525, 150, 210, 22);

        textpriceseateco.setText("jTextField2");
        add(textpriceseateco);
        textpriceseateco.setBounds(830, 150, 120, 20);

        textnbrseatsbuisness.setText("jTextField2");
        add(textnbrseatsbuisness);
        textnbrseatsbuisness.setBounds(830, 220, 120, 20);

        textpriceseatbuisness.setText("jTextField2");
        add(textpriceseatbuisness);
        textpriceseatbuisness.setBounds(830, 270, 120, 20);

        nbrseatsbuisness.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        nbrseatsbuisness.setText("Number of seats (buisness class):");
        add(nbrseatsbuisness);
        nbrseatsbuisness.setBounds(525, 220, 240, 22);

        priceseatbuisness.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        priceseatbuisness.setText("Price of a seat for this class:");
        add(priceseatbuisness);
        priceseatbuisness.setBounds(525, 270, 220, 22);

        numberseatsfrst.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        numberseatsfrst.setText("Number of seats (first class):");
        add(numberseatsfrst);
        numberseatsfrst.setBounds(525, 340, 240, 22);

        pricefirst.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        pricefirst.setText("Price of a seat for this class:");
        add(pricefirst);
        pricefirst.setBounds(525, 390, 220, 22);

        textpriceseatfirst.setText("jTextField2");
        add(textpriceseatfirst);
        textpriceseatfirst.setBounds(830, 390, 120, 20);

        textnbrseatfirst.setText("jTextField2");
        add(textnbrseatfirst);
        textnbrseatfirst.setBounds(830, 340, 120, 20);

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
                        if((FlightController.CheckFlightInfo(choicedeparturedate.getDate(), choicearrivaldate.getDate())))
                    {
                        Timestamp dateDeparture=new Timestamp(choicedeparturedate.getDate().getYear(),choicedeparturedate.getDate().getMonth(),
                        choicedeparturedate.getDate().getDay(),Integer.parseInt(jComboBox3.getSelectedItem().toString()),Integer.parseInt(jComboBox1.getSelectedItem().toString()),0,0);
                
                        Timestamp dateArrival=new Timestamp(choicearrivaldate.getDate().getYear(),choicearrivaldate.getDate().getMonth(),
                        choicearrivaldate.getDate().getDay(),Integer.parseInt(jComboBox4.getSelectedItem().toString()),Integer.parseInt(jComboBox2.getSelectedItem().toString()),0,0);
                         FlightController.addFlight( ((Airplane)choiceairplane.getSelectedItem()).getIdAirplane() , "WorldAirline",((Airport) choicedepartureaiport.getSelectedItem()).getIdAirport() , ((Airport) choicearrivalairport.getSelectedItem()).getIdAirport(),dateDeparture  , dateArrival);
                    }
                }
              
        });
        add(add);
        add.setBounds(450, 470, 73, 23);
        
        choicearrivalairport.setModel(new DefaultComboBoxModel(AirportController.getAllAirports()));
        add(choicearrivalairport);
        choicearrivalairport.setBounds(250, 350, 120, 20);
        
        

        arrivalairport.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        arrivalairport.setText("Arrival Airport:");
        add(arrivalairport);
        arrivalairport.setBounds(50, 350, 140, 22);

        departureairport.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        departureairport.setText("Departure Airport:");
        add(departureairport);
        departureairport.setBounds(50, 300, 140, 22);

        choicedepartureaiport.setModel(new DefaultComboBoxModel(AirportController.getAllAirports()));
        add(choicedepartureaiport);
        choicedepartureaiport.setBounds(250, 300, 120, 20);

        choiceairplane.setModel(new DefaultComboBoxModel(AirplaneController.getAllAirports()));
        add(choiceairplane);
        choiceairplane.setBounds(250, 250, 120, 20);

        airplane.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        airplane.setText("Airplane:");
        add(airplane);
        airplane.setBounds(50, 250, 100, 22);

        arrivaldate.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        arrivaldate.setText("Arrival Date:");
        add(arrivaldate);
        arrivaldate.setBounds(50, 170, 140, 22);
        add(choicearrivaldate);
        choicearrivaldate.setBounds(250, 170, 120, 20);
        add(choicedeparturedate);
        choicedeparturedate.setBounds(250, 100, 120, 20);

        departuredate.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        departuredate.setText("Departure Date:");
        add(departuredate);
        departuredate.setBounds(50, 100, 140, 22);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20","21", "22", "23", "24", "25", "26", "27", "28", "29", "30","31", "32", "33", "34", "35", "36", "37", "38", "39", "40","41", "42", "43", "44", "45", "46", "47", "48", "49", "50","51", "52", "53", "54", "55", "56", "57", "58", "59", "60"  }));
        add(jComboBox1);
        jComboBox1.setBounds(330, 130, 40, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20","21", "22", "23", "24", "25", "26", "27", "28", "29", "30","31", "32", "33", "34", "35", "36", "37", "38", "39", "40","41", "42", "43", "44", "45", "46", "47", "48", "49", "50","51", "52", "53", "54", "55", "56", "57", "58", "59", "60" }));
        add(jComboBox2);
        jComboBox2.setBounds(330, 200, 40, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20","21", "22", "23", "24" }));
        add(jComboBox3);
        jComboBox3.setBounds(260, 130, 40, 20);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20","21", "22", "23", "24" }));
        add(jComboBox4);
        jComboBox4.setBounds(260, 200, 40, 20);

        jLabel1.setText("H");
        add(jLabel1);
        jLabel1.setBounds(300, 200, 10, 14);

        jLabel2.setText("H");
        add(jLabel2);
        jLabel2.setBounds(300, 130, 10, 14);

        jLabel3.setText("Min");
        add(jLabel3);
        jLabel3.setBounds(370, 200, 34, 14);

        jLabel4.setText("Min");
        add(jLabel4);
        jLabel4.setBounds(370, 130, 34, 14);
    }// </editor-fold>                        

 

    // Variables declaration - do not modify                     
    private javax.swing.JButton add;
    private javax.swing.JLabel addaflight;
    private javax.swing.JLabel airplane;
    private javax.swing.JLabel arrivalairport;
    private javax.swing.JLabel arrivaldate;
    private javax.swing.JComboBox choiceairplane;
    private javax.swing.JComboBox choicearrivalairport;
    private com.toedter.calendar.JDateChooser choicearrivaldate;
    private javax.swing.JComboBox choicedepartureaiport;
    private com.toedter.calendar.JDateChooser choicedeparturedate;
    private javax.swing.JLabel departureairport;
    private javax.swing.JLabel departuredate;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel nbrseatsbuisness;
    private javax.swing.JLabel nbrseatseco;
    private javax.swing.JLabel numberseatsfrst;
    private javax.swing.JLabel pricefirst;
    private javax.swing.JLabel priceseatbuisness;
    private javax.swing.JLabel priceseateco;
    private javax.swing.JTextField textnbrseatfirst;
    private javax.swing.JTextField textnbrseatsbuisness;
    private javax.swing.JTextField textpriceseatbuisness;
    private javax.swing.JTextField textpriceseateco;
    private javax.swing.JTextField textpriceseatfirst;
    private javax.swing.JTextField textpriceseatseco;
    // End of variables declaration                   
}
