/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.BookingController;

/**
 *
 * @author bibes
 */
public class EmployeeUpdateBooking extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeUpdateBooking
     */
    private  int bookingNo;
    public EmployeeUpdateBooking(int bookingNo) {
        initComponents();
        this.bookingNo=bookingNo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel1.setText("Price of the class:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 290, 160, 30);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel2.setText("Update:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 20, 160, 30);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel3.setText("Name of the flight:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 90, 160, 30);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel4.setText("Number of tickets:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 140, 160, 30);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel5.setText("Date of departure:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 190, 160, 30);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel6.setText("Classe name:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 240, 160, 30);

        jTextField1.setText(String.valueOf(BookingController.getBooking(bookingNo).getTickets().get(0).getFlight().getIdFlight()));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
          
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(240, 90, 120, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1","2","3","4","5","6","7","8","9","10" }));
        jComboBox1.setSelectedIndex(BookingController.getBooking(bookingNo).getTickets().size()-1);
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(240, 240, 120, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Economic Class", "Buisness Class", "First Class" }));
        jComboBox3.setSelectedItem(BookingController.getBooking(bookingNo).getTickets().get(0).getSeat().getClassName());
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(240, 140, 120, 20);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(240, 190, 120, 20);

        jButton1.setText("Update");
        jPanel1.add(jButton1);
        jButton1.setBounds(180, 390, 67, 23);

        jTextField2.setText("");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
      
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(240, 290, 120, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

 

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration                   
}
