/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author bibes
 */
public class EmployeeAddFlightTest extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeAddFlightTest
     */
    public EmployeeAddFlightTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textpriceseatseco = new javax.swing.JTextField();
        addaflight = new javax.swing.JLabel();
        nbrseatseco = new javax.swing.JLabel();
        priceseateco = new javax.swing.JLabel();
        textpriceseateco = new javax.swing.JTextField();
        textnbrseatsbuisness = new javax.swing.JTextField();
        textpriceseatbuisness = new javax.swing.JTextField();
        nbrseatsbuisness = new javax.swing.JLabel();
        priceseatbuisness = new javax.swing.JLabel();
        numberseatsfrst = new javax.swing.JLabel();
        pricefirst = new javax.swing.JLabel();
        textpriceseatfirst = new javax.swing.JTextField();
        textnbrseatfirst = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        choicearrivalairport = new javax.swing.JComboBox();
        arrivalairport = new javax.swing.JLabel();
        departureairport = new javax.swing.JLabel();
        choicedepartureaiport = new javax.swing.JComboBox();
        choiceairplane = new javax.swing.JComboBox();
        airplane = new javax.swing.JLabel();
        arrivaldate = new javax.swing.JLabel();
        choicearrivaldate = new com.toedter.calendar.JDateChooser();
        choicedeparturedate = new com.toedter.calendar.JDateChooser();
        departuredate = new javax.swing.JLabel();
        nameoftheflight = new javax.swing.JLabel();
        textnameflight = new javax.swing.JTextField();

        setLayout(null);

        textpriceseatseco.setText("jTextField2");
        add(textpriceseatseco);
        textpriceseatseco.setBounds(830, 100, 120, 20);

        addaflight.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        addaflight.setText("Add a flight:");
        add(addaflight);
        addaflight.setBounds(430, 20, 140, 32);

        nbrseatseco.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        nbrseatseco.setText("Number of seats (economic class):");
        add(nbrseatseco);
        nbrseatseco.setBounds(525, 100, 236, 22);

        priceseateco.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        priceseateco.setText("Price of a seat for this class:");
        add(priceseateco);
        priceseateco.setBounds(525, 150, 210, 22);

        textpriceseateco.setText("jTextField2");
        add(textpriceseateco);
        textpriceseateco.setBounds(830, 150, 120, 20);

        textnbrseatsbuisness.setText("jTextField2");
        add(textnbrseatsbuisness);
        textnbrseatsbuisness.setBounds(830, 220, 120, 20);

        textpriceseatbuisness.setText("jTextField2");
        add(textpriceseatbuisness);
        textpriceseatbuisness.setBounds(830, 270, 120, 20);

        nbrseatsbuisness.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        nbrseatsbuisness.setText("Number of seats (buisness class):");
        add(nbrseatsbuisness);
        nbrseatsbuisness.setBounds(525, 220, 240, 22);

        priceseatbuisness.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        priceseatbuisness.setText("Price of a seat for this class:");
        add(priceseatbuisness);
        priceseatbuisness.setBounds(525, 270, 220, 22);

        numberseatsfrst.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        numberseatsfrst.setText("Number of seats (first class):");
        add(numberseatsfrst);
        numberseatsfrst.setBounds(525, 340, 240, 22);

        pricefirst.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        pricefirst.setText("Price of a seat for this class:");
        add(pricefirst);
        pricefirst.setBounds(525, 390, 220, 22);

        textpriceseatfirst.setText("jTextField2");
        add(textpriceseatfirst);
        textpriceseatfirst.setBounds(830, 390, 120, 20);

        textnbrseatfirst.setText("jTextField2");
        add(textnbrseatfirst);
        textnbrseatfirst.setBounds(830, 340, 120, 20);

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        add(add);
        add.setBounds(450, 470, 73, 23);

        choicearrivalairport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(choicearrivalairport);
        choicearrivalairport.setBounds(250, 350, 120, 20);

        arrivalairport.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        arrivalairport.setText("Arrival Airport:");
        add(arrivalairport);
        arrivalairport.setBounds(50, 350, 140, 22);

        departureairport.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        departureairport.setText("Departure Airport:");
        add(departureairport);
        departureairport.setBounds(50, 300, 140, 22);

        choicedepartureaiport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(choicedepartureaiport);
        choicedepartureaiport.setBounds(250, 300, 120, 20);

        choiceairplane.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(choiceairplane);
        choiceairplane.setBounds(250, 250, 120, 20);

        airplane.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        airplane.setText("Airplane:");
        add(airplane);
        airplane.setBounds(50, 250, 100, 22);

        arrivaldate.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        arrivaldate.setText("Arrival Date:");
        add(arrivaldate);
        arrivaldate.setBounds(50, 200, 140, 22);
        add(choicearrivaldate);
        choicearrivaldate.setBounds(250, 200, 120, 20);
        add(choicedeparturedate);
        choicedeparturedate.setBounds(250, 150, 120, 20);

        departuredate.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        departuredate.setText("Departure Date:");
        add(departuredate);
        departuredate.setBounds(50, 150, 140, 22);

        nameoftheflight.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        nameoftheflight.setText("Name of the flight:");
        add(nameoftheflight);
        nameoftheflight.setBounds(50, 100, 140, 16);

        textnameflight.setText("jTextField2");
        add(textnameflight);
        textnameflight.setBounds(250, 100, 120, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JLabel addaflight;
    private javax.swing.JLabel airplane;
    private javax.swing.JLabel arrivalairport;
    private javax.swing.JLabel arrivaldate;
    private javax.swing.JComboBox choiceairplane;
    private javax.swing.JComboBox choicearrivalairport;
    private com.toedter.calendar.JDateChooser choicearrivaldate;
    private javax.swing.JComboBox choicedepartureaiport;
    private com.toedter.calendar.JDateChooser choicedeparturedate;
    private javax.swing.JLabel departureairport;
    private javax.swing.JLabel departuredate;
    private javax.swing.JLabel nameoftheflight;
    private javax.swing.JLabel nbrseatsbuisness;
    private javax.swing.JLabel nbrseatseco;
    private javax.swing.JLabel numberseatsfrst;
    private javax.swing.JLabel pricefirst;
    private javax.swing.JLabel priceseatbuisness;
    private javax.swing.JLabel priceseateco;
    private javax.swing.JTextField textnameflight;
    private javax.swing.JTextField textnbrseatfirst;
    private javax.swing.JTextField textnbrseatsbuisness;
    private javax.swing.JTextField textpriceseatbuisness;
    private javax.swing.JTextField textpriceseateco;
    private javax.swing.JTextField textpriceseatfirst;
    private javax.swing.JTextField textpriceseatseco;
    // End of variables declaration//GEN-END:variables
}
