/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DataAcessObjectImpl.FlightDAOImpl;
import controller.SearchFlightsTableModel;
import java.util.ArrayList;
import model.Flight;

/**
 *
 * @author Unknow
 */
public class EmployeeHomeTest extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeHome
     */
    public EmployeeHomeTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        DepartureScrollPane = new javax.swing.JScrollPane();
        searchDeapartureFlights = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        manageFlight = new javax.swing.JMenu();
        SearchFlight = new javax.swing.JMenuItem();
        AddFlight = new javax.swing.JMenuItem();
        Update_DeleteFlight = new javax.swing.JMenuItem();
        manageBookings = new javax.swing.JMenu();
        UpdateBooking = new javax.swing.JMenuItem();
        DeleteBooking = new javax.swing.JMenuItem();
        ManageCoupons = new javax.swing.JMenu();
        AddCoupon = new javax.swing.JMenuItem();
        SearchCoupon = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(200, 191, 191));
        jPanel1.setLayout(null);

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setVisible(true);

        ArrayList<Flight> flights =  new ArrayList<Flight>();
        flights.add(new FlightDAOImpl().find(5));
        System.out.println(flights.get(0).getIdFlight());
        SearchFlightsTableModel  model = new SearchFlightsTableModel(flights);
        searchDeapartureFlights.setFont(new java.awt.Font("Yu Gothic UI", 0, 12));
        searchDeapartureFlights.setModel(model);
        searchDeapartureFlights.setFocusable(false);
        searchDeapartureFlights.setGridColor(new java.awt.Color(0, 0, 0));
        searchDeapartureFlights.setOpaque(false);
        searchDeapartureFlights.setRowHeight(20);
        searchDeapartureFlights.setSelectionBackground(new java.awt.Color(200, 191, 191));
        searchDeapartureFlights.setShowHorizontalLines(false);
        searchDeapartureFlights.setShowVerticalLines(false);
        searchDeapartureFlights.getTableHeader().setReorderingAllowed(false);
        DepartureScrollPane.setViewportView(searchDeapartureFlights);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DepartureScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DepartureScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        jPanel1.add(jInternalFrame1);
        jInternalFrame1.setBounds(0, 0, 820, 480);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1100, 570);

        manageFlight.setText("Manage flights");

        SearchFlight.setText("Search Fligt");
        SearchFlight.setToolTipText("");
        SearchFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFlightActionPerformed(evt);
            }
        });
        manageFlight.add(SearchFlight);

        AddFlight.setText("Add Flight");
        manageFlight.add(AddFlight);

        Update_DeleteFlight.setText("Update/Delete Flight");
        Update_DeleteFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_DeleteFlightActionPerformed(evt);
            }
        });
        manageFlight.add(Update_DeleteFlight);

        menuBar.add(manageFlight);

        manageBookings.setText("Manage bookings");

        UpdateBooking.setText("SearchBooking");
        manageBookings.add(UpdateBooking);

        DeleteBooking.setText("Update/Delete Booking");
        manageBookings.add(DeleteBooking);

        menuBar.add(manageBookings);

        ManageCoupons.setText("Manage coupons");

        AddCoupon.setText("Add Coupon");
        ManageCoupons.add(AddCoupon);

        SearchCoupon.setText("Search/Delete Coupon");
        SearchCoupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCouponActionPerformed(evt);
            }
        });
        ManageCoupons.add(SearchCoupon);

        menuBar.add(ManageCoupons);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Update_DeleteFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_DeleteFlightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_DeleteFlightActionPerformed

    private void SearchCouponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCouponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchCouponActionPerformed

    private void SearchFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFlightActionPerformed
        // TODO add your handling code here:
        SearchFlight SearchForAFlight=new SearchFlight();
    }//GEN-LAST:event_SearchFlightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeHomeTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeHomeTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeHomeTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeHomeTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeHomeTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddCoupon;
    private javax.swing.JMenuItem AddFlight;
    private javax.swing.JMenuItem DeleteBooking;
    private javax.swing.JScrollPane DepartureScrollPane;
    private javax.swing.JMenu ManageCoupons;
    private javax.swing.JMenuItem SearchCoupon;
    private javax.swing.JMenuItem SearchFlight;
    private javax.swing.JMenuItem UpdateBooking;
    private javax.swing.JMenuItem Update_DeleteFlight;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu manageBookings;
    private javax.swing.JMenu manageFlight;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTable searchDeapartureFlights;
    // End of variables declaration//GEN-END:variables
}
