/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author bibes
 */
public class EmployeeSearchDeleteCouponTest extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeSearchDeleteCouponTest
     */
    public EmployeeSearchDeleteCouponTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title3 = new javax.swing.JLabel();
        search3 = new javax.swing.JButton();
        textidflight3 = new javax.swing.JTextField();
        idflight3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setLayout(null);

        title3.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        title3.setText("Search Coupons:");
        add(title3);
        title3.setBounds(380, 10, 150, 30);

        search3.setText("research");
        search3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search3ActionPerformed(evt);
            }
        });
        add(search3);
        search3.setBounds(400, 60, 90, 23);

        textidflight3.setText("jTextField1");
        textidflight3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textidflight3ActionPerformed(evt);
            }
        });
        add(textidflight3);
        textidflight3.setBounds(230, 63, 150, 20);

        idflight3.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        idflight3.setText("Enter the id of the booking: ");
        add(idflight3);
        idflight3.setBounds(30, 60, 200, 22);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        add(jScrollPane4);
        jScrollPane4.setBounds(140, 160, 630, 330);

        jButton3.setText("Delete");
        add(jButton3);
        jButton3.setBounds(840, 420, 73, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void search3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search3ActionPerformed

    private void textidflight3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textidflight3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textidflight3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idflight3;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton search3;
    private javax.swing.JTextField textidflight3;
    private javax.swing.JLabel title3;
    // End of variables declaration//GEN-END:variables
}
