/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.UIManager;

/**
 *
 * @author Unknow
 */
public class MyAccountTest extends javax.swing.JFrame {

    /**
     * Creates new form MyAccount
     */
    public MyAccountTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myTicketDetailsPanel = new javax.swing.JPanel();
        myTicketDetails = new javax.swing.JLabel();
        previous4 = new javax.swing.JButton();
        to = new javax.swing.JLabel();
        arrivalTimeDate = new javax.swing.JLabel();
        flight = new javax.swing.JLabel();
        to2 = new javax.swing.JLabel();
        arrivalDateTime2 = new javax.swing.JLabel();
        flight2 = new javax.swing.JLabel();
        nameOfPassenger = new javax.swing.JLabel();
        nameOfPasenger2 = new javax.swing.JLabel();
        from = new javax.swing.JLabel();
        from2 = new javax.swing.JLabel();
        departureTimeDate = new javax.swing.JLabel();
        departureTimeDate2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(55, 112, 155));
        getContentPane().setLayout(null);

        myTicketDetailsPanel.setBackground(new java.awt.Color(55, 112, 155));
        myTicketDetailsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        myTicketDetailsPanel.setLayout(null);

        myTicketDetails.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        myTicketDetails.setForeground(new java.awt.Color(255, 255, 255));
        myTicketDetails.setText("My Ticket Details");
        myTicketDetailsPanel.add(myTicketDetails);
        myTicketDetails.setBounds(170, 10, 200, 40);

        previous4.setBackground(new java.awt.Color(255, 255, 255));
        previous4.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 10)); // NOI18N
        previous4.setText("Previous");
        previous4.setBorder(null);
        previous4.setBorderPainted(false);
        previous4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        previous4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previous4ActionPerformed(evt);
            }
        });
        myTicketDetailsPanel.add(previous4);
        previous4.setBounds(3, 555, 60, 20);

        to.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        to.setForeground(new java.awt.Color(255, 255, 255));
        to.setText("To");
        myTicketDetailsPanel.add(to);
        to.setBounds(60, 240, 160, 30);

        arrivalTimeDate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        arrivalTimeDate.setForeground(new java.awt.Color(255, 255, 255));
        arrivalTimeDate.setText("Arrival Date Time");
        myTicketDetailsPanel.add(arrivalTimeDate);
        arrivalTimeDate.setBounds(310, 240, 170, 30);

        flight.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        flight.setForeground(new java.awt.Color(255, 255, 255));
        flight.setText("Flight");
        myTicketDetailsPanel.add(flight);
        flight.setBounds(310, 110, 90, 30);

        to2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        to2.setForeground(new java.awt.Color(255, 255, 255));
        to2.setText("jLabel1");
        myTicketDetailsPanel.add(to2);
        to2.setBounds(60, 260, 70, 20);

        arrivalDateTime2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        arrivalDateTime2.setForeground(new java.awt.Color(255, 255, 255));
        arrivalDateTime2.setText("jLabel1");
        myTicketDetailsPanel.add(arrivalDateTime2);
        arrivalDateTime2.setBounds(310, 260, 70, 20);

        flight2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        flight2.setForeground(new java.awt.Color(255, 255, 255));
        flight2.setText("jLabel1");
        myTicketDetailsPanel.add(flight2);
        flight2.setBounds(310, 130, 70, 20);

        nameOfPassenger.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        nameOfPassenger.setForeground(new java.awt.Color(255, 255, 255));
        nameOfPassenger.setText("Name Of Passenger");
        myTicketDetailsPanel.add(nameOfPassenger);
        nameOfPassenger.setBounds(60, 110, 180, 30);

        nameOfPasenger2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        nameOfPasenger2.setForeground(new java.awt.Color(255, 255, 255));
        nameOfPasenger2.setText("jLabel1");
        myTicketDetailsPanel.add(nameOfPasenger2);
        nameOfPasenger2.setBounds(60, 130, 70, 20);

        from.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        from.setForeground(new java.awt.Color(255, 255, 255));
        from.setText("From");
        myTicketDetailsPanel.add(from);
        from.setBounds(60, 180, 160, 30);

        from2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        from2.setForeground(new java.awt.Color(255, 255, 255));
        from2.setText("jLabel1");
        myTicketDetailsPanel.add(from2);
        from2.setBounds(60, 200, 70, 20);

        departureTimeDate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        departureTimeDate.setForeground(new java.awt.Color(255, 255, 255));
        departureTimeDate.setText("Departure Date Time");
        myTicketDetailsPanel.add(departureTimeDate);
        departureTimeDate.setBounds(310, 180, 170, 30);

        departureTimeDate2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        departureTimeDate2.setForeground(new java.awt.Color(255, 255, 255));
        departureTimeDate2.setText("jLabel1");
        myTicketDetailsPanel.add(departureTimeDate2);
        departureTimeDate2.setBounds(310, 200, 70, 20);

        getContentPane().add(myTicketDetailsPanel);
        myTicketDetailsPanel.setBounds(0, 0, 510, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void previous4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previous4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_previous4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      	


try {

UIManager.setLookAndFeel( "com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
}
catch (ClassNotFoundException ex) {
}catch (InstantiationException ex) {

} catch (IllegalAccessException ex) {
} catch (javax.swing.UnsupportedLookAndFeelException ex) {
}
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyAccountTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrivalDateTime2;
    private javax.swing.JLabel arrivalTimeDate;
    private javax.swing.JLabel departureTimeDate;
    private javax.swing.JLabel departureTimeDate2;
    private javax.swing.JLabel flight;
    private javax.swing.JLabel flight2;
    private javax.swing.JLabel from;
    private javax.swing.JLabel from2;
    private javax.swing.JLabel myTicketDetails;
    private javax.swing.JPanel myTicketDetailsPanel;
    private javax.swing.JLabel nameOfPasenger2;
    private javax.swing.JLabel nameOfPassenger;
    private javax.swing.JButton previous4;
    private javax.swing.JLabel to;
    private javax.swing.JLabel to2;
    // End of variables declaration//GEN-END:variables
}
