/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.UIManager;

/**
 *
 * @author Unknow
 */
public class MyAccountTest extends javax.swing.JFrame {

    /**
     * Creates new form MyAccount
     */
    public MyAccountTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myTicketsPanel = new javax.swing.JPanel();
        myTickets = new javax.swing.JLabel();
        previous3 = new javax.swing.JButton();
        myTicketsScrollPane = new javax.swing.JScrollPane();
        myTicketsTable = new javax.swing.JTable();
        viewTicket = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(55, 112, 155));
        getContentPane().setLayout(null);

        myTicketsPanel.setBackground(new java.awt.Color(55, 112, 155));
        myTicketsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        myTicketsPanel.setLayout(null);

        myTickets.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        myTickets.setForeground(new java.awt.Color(255, 255, 255));
        myTickets.setText("My Tickets");
        myTicketsPanel.add(myTickets);
        myTickets.setBounds(200, 10, 140, 40);

        previous3.setBackground(new java.awt.Color(255, 255, 255));
        previous3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 10)); // NOI18N
        previous3.setText("Previous");
        previous3.setBorder(null);
        previous3.setBorderPainted(false);
        previous3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        previous3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previous3ActionPerformed(evt);
            }
        });
        myTicketsPanel.add(previous3);
        previous3.setBounds(3, 555, 60, 20);

        myTicketsTable.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        myTicketsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        myTicketsTable.setToolTipText("");
        myTicketsTable.setSelectionBackground(new java.awt.Color(0, 204, 0));
        myTicketsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        myTicketsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        myTicketsTable.setShowGrid(true);
        myTicketsScrollPane.setViewportView(myTicketsTable);

        myTicketsPanel.add(myTicketsScrollPane);
        myTicketsScrollPane.setBounds(25, 90, 480, 390);

        viewTicket.setBackground(new java.awt.Color(255, 255, 255));
        viewTicket.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        viewTicket.setText("View Ticket");
        viewTicket.setBorder(null);
        viewTicket.setBorderPainted(false);
        viewTicket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTicketActionPerformed(evt);
            }
        });
        myTicketsPanel.add(viewTicket);
        viewTicket.setBounds(170, 520, 190, 30);

        getContentPane().add(myTicketsPanel);
        myTicketsPanel.setBounds(0, 0, 530, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void previous3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previous3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_previous3ActionPerformed

    private void viewTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTicketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewTicketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      	


try {

UIManager.setLookAndFeel( "com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
}
catch (ClassNotFoundException ex) {
}catch (InstantiationException ex) {

} catch (IllegalAccessException ex) {
} catch (javax.swing.UnsupportedLookAndFeelException ex) {
}
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyAccountTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel myTickets;
    private javax.swing.JPanel myTicketsPanel;
    private javax.swing.JScrollPane myTicketsScrollPane;
    private javax.swing.JTable myTicketsTable;
    private javax.swing.JButton previous3;
    private javax.swing.JButton viewTicket;
    // End of variables declaration//GEN-END:variables
}
