/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Unknow
 */
public class MyAccountTest extends javax.swing.JFrame {

    /**
     * Creates new form MyAccount
     */
    public MyAccountTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        myAccount = new javax.swing.JLabel();
        personalInfo = new javax.swing.JButton();
        personalInfo1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(55, 112, 155));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(55, 112, 155));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setLayout(null);

        myAccount.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        myAccount.setForeground(new java.awt.Color(255, 255, 255));
        myAccount.setIcon(new javax.swing.ImageIcon("D:\\GITHUB\\worldAirline\\img\\input-onlinepngtools.png")); // NOI18N
        myAccount.setText("My Account");
        myAccount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myAccount.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(myAccount);
        myAccount.setBounds(190, 20, 160, 150);

        personalInfo.setBackground(new java.awt.Color(255, 255, 255));
        personalInfo.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        personalInfo.setText("My Bookings");
        personalInfo.setBorder(null);
        personalInfo.setBorderPainted(false);
        personalInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        personalInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalInfoActionPerformed(evt);
            }
        });
        jPanel1.add(personalInfo);
        personalInfo.setBounds(140, 300, 230, 40);

        personalInfo1.setBackground(new java.awt.Color(255, 255, 255));
        personalInfo1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        personalInfo1.setText("My Personal Information");
        personalInfo1.setBorder(null);
        personalInfo1.setBorderPainted(false);
        personalInfo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        personalInfo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalInfo1ActionPerformed(evt);
            }
        });
        jPanel1.add(personalInfo1);
        personalInfo1.setBounds(140, 230, 230, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 530, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personalInfo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalInfo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personalInfo1ActionPerformed

    private void personalInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personalInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyAccountTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyAccountTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyAccountTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyAccountTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyAccountTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel myAccount;
    private javax.swing.JButton personalInfo;
    private javax.swing.JButton personalInfo1;
    // End of variables declaration//GEN-END:variables
}
