/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Unknow
 */
public class PassengerTest extends javax.swing.JFrame {

    /**
     * Creates new form PassengerTest
     */
    public PassengerTest() {
        initComponents();
        this.setSize(643,815);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        arrivalAirport1 = new javax.swing.JLabel();
        arrivalDateTime = new javax.swing.JLabel();
        arrival = new javax.swing.JLabel();
        to = new javax.swing.JLabel();
        departure = new javax.swing.JLabel();
        departureDateTime = new javax.swing.JLabel();
        from = new javax.swing.JLabel();
        departure1 = new javax.swing.JLabel();
        departureDateTime1 = new javax.swing.JLabel();
        arrival1 = new javax.swing.JLabel();
        arrivalDateTime1 = new javax.swing.JLabel();
        from1 = new javax.swing.JLabel();
        to1 = new javax.swing.JLabel();
        departurAirport1 = new javax.swing.JLabel();
        departurAirport2 = new javax.swing.JLabel();
        arrivalAirport2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(55, 112, 155));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Flight Infos");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(250, 10, 120, 40);

        arrivalAirport1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 20)); // NOI18N
        arrivalAirport1.setForeground(new java.awt.Color(255, 255, 255));
        arrivalAirport1.setText("Miami");
        jPanel1.add(arrivalAirport1);
        arrivalAirport1.setBounds(390, 130, 150, 27);

        arrivalDateTime.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 11)); // NOI18N
        arrivalDateTime.setForeground(new java.awt.Color(255, 255, 255));
        arrivalDateTime.setText("02/03/2020 at 08:45 P.M");
        jPanel1.add(arrivalDateTime);
        arrivalDateTime.setBounds(90, 265, 130, 14);

        arrival.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        arrival.setForeground(new java.awt.Color(255, 255, 255));
        arrival.setIcon(new javax.swing.ImageIcon("D:\\GITHUB\\worldAirline\\img\\output-onlinepngtools (7).png")); // NOI18N
        arrival.setText("Arrival");
        jPanel1.add(arrival);
        arrival.setBounds(50, 240, 160, 30);

        to.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        to.setForeground(new java.awt.Color(255, 255, 255));
        to.setText("To");
        jPanel1.add(to);
        to.setBounds(280, 250, 50, 30);

        departure.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        departure.setForeground(new java.awt.Color(255, 255, 255));
        departure.setIcon(new javax.swing.ImageIcon("D:\\GITHUB\\worldAirline\\img\\output-onlinepngtools (7).png")); // NOI18N
        departure.setText("Departure");
        jPanel1.add(departure);
        departure.setBounds(50, 190, 160, 30);

        departureDateTime.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 11)); // NOI18N
        departureDateTime.setForeground(new java.awt.Color(255, 255, 255));
        departureDateTime.setText("02/03/2020 at 08:45 P.M");
        jPanel1.add(departureDateTime);
        departureDateTime.setBounds(90, 215, 130, 14);

        from.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        from.setForeground(new java.awt.Color(255, 255, 255));
        from.setText("From");
        jPanel1.add(from);
        from.setBounds(280, 190, 50, 30);

        departure1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        departure1.setForeground(new java.awt.Color(255, 255, 255));
        departure1.setIcon(new javax.swing.ImageIcon("D:\\GITHUB\\worldAirline\\img\\output-onlinepngtools (7).png")); // NOI18N
        departure1.setText("Departure");
        jPanel1.add(departure1);
        departure1.setBounds(50, 70, 160, 30);

        departureDateTime1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 11)); // NOI18N
        departureDateTime1.setForeground(new java.awt.Color(255, 255, 255));
        departureDateTime1.setText("02/03/2020 at 08:45 P.M");
        jPanel1.add(departureDateTime1);
        departureDateTime1.setBounds(90, 95, 130, 14);

        arrival1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        arrival1.setForeground(new java.awt.Color(255, 255, 255));
        arrival1.setIcon(new javax.swing.ImageIcon("D:\\GITHUB\\worldAirline\\img\\output-onlinepngtools (7).png")); // NOI18N
        arrival1.setText("Arrival");
        jPanel1.add(arrival1);
        arrival1.setBounds(50, 120, 160, 30);

        arrivalDateTime1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 11)); // NOI18N
        arrivalDateTime1.setForeground(new java.awt.Color(255, 255, 255));
        arrivalDateTime1.setText("02/03/2020 at 08:45 P.M");
        jPanel1.add(arrivalDateTime1);
        arrivalDateTime1.setBounds(90, 145, 130, 14);

        from1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        from1.setForeground(new java.awt.Color(255, 255, 255));
        from1.setText("From");
        jPanel1.add(from1);
        from1.setBounds(280, 70, 50, 30);

        to1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        to1.setForeground(new java.awt.Color(255, 255, 255));
        to1.setText("To");
        jPanel1.add(to1);
        to1.setBounds(280, 130, 50, 30);

        departurAirport1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 20)); // NOI18N
        departurAirport1.setForeground(new java.awt.Color(255, 255, 255));
        departurAirport1.setText("Miami");
        jPanel1.add(departurAirport1);
        departurAirport1.setBounds(390, 70, 150, 27);

        departurAirport2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 20)); // NOI18N
        departurAirport2.setForeground(new java.awt.Color(255, 255, 255));
        departurAirport2.setText("Miami");
        jPanel1.add(departurAirport2);
        departurAirport2.setBounds(390, 190, 150, 27);

        arrivalAirport2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 20)); // NOI18N
        arrivalAirport2.setForeground(new java.awt.Color(255, 255, 255));
        arrivalAirport2.setText("Miami");
        jPanel1.add(arrivalAirport2);
        arrivalAirport2.setBounds(390, 250, 150, 27);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 630, 300);

        jScrollPane1.setBackground(new java.awt.Color(200, 191, 191));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel3.setText("Passenger");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(250, 20, 120, 40);

        jTextField4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(51, 51, 51));
        jTextField4.setText("Enter email adress...");
        jTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField4);
        jTextField4.setBounds(210, 225, 160, 30);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel4.setText("Email");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(50, 230, 50, 25);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel6.setText("Email");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(50, 310, 50, 25);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel7.setText("Email");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(50, 155, 50, 25);

        jTextField5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(51, 51, 51));
        jTextField5.setText("Enter email adress...");
        jTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField5);
        jTextField5.setBounds(210, 305, 160, 30);

        jTextField1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(220, 150, 130, 30);

        jScrollPane1.setViewportView(jPanel2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 300, 630, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassengerTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassengerTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassengerTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassengerTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassengerTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrival;
    private javax.swing.JLabel arrival1;
    private javax.swing.JLabel arrivalAirport1;
    private javax.swing.JLabel arrivalAirport2;
    private javax.swing.JLabel arrivalDateTime;
    private javax.swing.JLabel arrivalDateTime1;
    private javax.swing.JLabel departurAirport1;
    private javax.swing.JLabel departurAirport2;
    private javax.swing.JLabel departure;
    private javax.swing.JLabel departure1;
    private javax.swing.JLabel departureDateTime;
    private javax.swing.JLabel departureDateTime1;
    private javax.swing.JLabel from;
    private javax.swing.JLabel from1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel to;
    private javax.swing.JLabel to1;
    // End of variables declaration//GEN-END:variables
}
