/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Unknow
 */
public class PassengerTest extends javax.swing.JFrame {

    /**
     * Creates new form PassengerTest
     */
    public PassengerTest() {
        initComponents();
        this.setSize(643,815);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        arrivalAirport1 = new javax.swing.JLabel();
        arrivalDateTime = new javax.swing.JLabel();
        arrival = new javax.swing.JLabel();
        to = new javax.swing.JLabel();
        departure = new javax.swing.JLabel();
        departureDateTime = new javax.swing.JLabel();
        from = new javax.swing.JLabel();
        departure1 = new javax.swing.JLabel();
        departureDateTime1 = new javax.swing.JLabel();
        arrival1 = new javax.swing.JLabel();
        arrivalDateTime1 = new javax.swing.JLabel();
        from1 = new javax.swing.JLabel();
        to1 = new javax.swing.JLabel();
        departurAirport1 = new javax.swing.JLabel();
        departurAirport2 = new javax.swing.JLabel();
        arrivalAirport2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        panelMyaccount = new javax.swing.JPanel();
        myAccount = new javax.swing.JLabel();
        personalInfo = new javax.swing.JButton();
        personalInfo1 = new javax.swing.JButton();
        myPersonalInfos = new javax.swing.JPanel();
        email = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        firstName = new javax.swing.JLabel();
        lastName = new javax.swing.JLabel();
        adress = new javax.swing.JLabel();
        birthDate = new javax.swing.JLabel();
        ageCategory = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        adressField = new javax.swing.JTextField();
        telephoneNulberField = new javax.swing.JTextField();
        birthDateDate = new com.toedter.calendar.JDateChooser();
        passwordField = new javax.swing.JPasswordField();
        myPersonalInfo = new javax.swing.JLabel();
        previous = new javax.swing.JButton();
        telephoneNumber = new javax.swing.JLabel();
        ageCategory1 = new javax.swing.JLabel();
        save1 = new javax.swing.JButton();
        myBookingsPanel = new javax.swing.JPanel();
        myBookings = new javax.swing.JLabel();
        previous1 = new javax.swing.JButton();
        bookingScrollPane = new javax.swing.JScrollPane();
        myBookingsTable = new javax.swing.JTable();
        getBooking = new javax.swing.JButton();
        myTicketsPanel = new javax.swing.JPanel();
        myTickets = new javax.swing.JLabel();
        previous3 = new javax.swing.JButton();
        myTicketsScrollPane = new javax.swing.JScrollPane();
        myTicketsTable = new javax.swing.JTable();
        viewTicket = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(55, 112, 155));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Flight Infos");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(250, 10, 120, 40);

        arrivalAirport1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 20)); // NOI18N
        arrivalAirport1.setForeground(new java.awt.Color(255, 255, 255));
        arrivalAirport1.setText("Miami");
        jPanel1.add(arrivalAirport1);
        arrivalAirport1.setBounds(390, 130, 150, 27);

        arrivalDateTime.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 11)); // NOI18N
        arrivalDateTime.setForeground(new java.awt.Color(255, 255, 255));
        arrivalDateTime.setText("02/03/2020 at 08:45 P.M");
        jPanel1.add(arrivalDateTime);
        arrivalDateTime.setBounds(90, 265, 130, 14);

        arrival.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        arrival.setForeground(new java.awt.Color(255, 255, 255));
        arrival.setIcon(new javax.swing.ImageIcon("D:\\GITHUB\\worldAirline\\img\\output-onlinepngtools (7).png")); // NOI18N
        arrival.setText("Arrival");
        jPanel1.add(arrival);
        arrival.setBounds(50, 240, 160, 30);

        to.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        to.setForeground(new java.awt.Color(255, 255, 255));
        to.setText("To");
        jPanel1.add(to);
        to.setBounds(280, 250, 50, 30);

        departure.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        departure.setForeground(new java.awt.Color(255, 255, 255));
        departure.setIcon(new javax.swing.ImageIcon("D:\\GITHUB\\worldAirline\\img\\output-onlinepngtools (7).png")); // NOI18N
        departure.setText("Departure");
        jPanel1.add(departure);
        departure.setBounds(50, 190, 160, 30);

        departureDateTime.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 11)); // NOI18N
        departureDateTime.setForeground(new java.awt.Color(255, 255, 255));
        departureDateTime.setText("02/03/2020 at 08:45 P.M");
        jPanel1.add(departureDateTime);
        departureDateTime.setBounds(90, 215, 130, 14);

        from.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        from.setForeground(new java.awt.Color(255, 255, 255));
        from.setText("From");
        jPanel1.add(from);
        from.setBounds(280, 190, 50, 30);

        departure1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        departure1.setForeground(new java.awt.Color(255, 255, 255));
        departure1.setIcon(new javax.swing.ImageIcon("D:\\GITHUB\\worldAirline\\img\\output-onlinepngtools (7).png")); // NOI18N
        departure1.setText("Departure");
        jPanel1.add(departure1);
        departure1.setBounds(50, 70, 160, 30);

        departureDateTime1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 11)); // NOI18N
        departureDateTime1.setForeground(new java.awt.Color(255, 255, 255));
        departureDateTime1.setText("02/03/2020 at 08:45 P.M");
        jPanel1.add(departureDateTime1);
        departureDateTime1.setBounds(90, 95, 130, 14);

        arrival1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        arrival1.setForeground(new java.awt.Color(255, 255, 255));
        arrival1.setIcon(new javax.swing.ImageIcon("D:\\GITHUB\\worldAirline\\img\\output-onlinepngtools (7).png")); // NOI18N
        arrival1.setText("Arrival");
        jPanel1.add(arrival1);
        arrival1.setBounds(50, 120, 160, 30);

        arrivalDateTime1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 11)); // NOI18N
        arrivalDateTime1.setForeground(new java.awt.Color(255, 255, 255));
        arrivalDateTime1.setText("02/03/2020 at 08:45 P.M");
        jPanel1.add(arrivalDateTime1);
        arrivalDateTime1.setBounds(90, 145, 130, 14);

        from1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        from1.setForeground(new java.awt.Color(255, 255, 255));
        from1.setText("From");
        jPanel1.add(from1);
        from1.setBounds(280, 70, 50, 30);

        to1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        to1.setForeground(new java.awt.Color(255, 255, 255));
        to1.setText("To");
        jPanel1.add(to1);
        to1.setBounds(280, 130, 50, 30);

        departurAirport1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 20)); // NOI18N
        departurAirport1.setForeground(new java.awt.Color(255, 255, 255));
        departurAirport1.setText("Miami");
        jPanel1.add(departurAirport1);
        departurAirport1.setBounds(390, 70, 150, 27);

        departurAirport2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 20)); // NOI18N
        departurAirport2.setForeground(new java.awt.Color(255, 255, 255));
        departurAirport2.setText("Miami");
        jPanel1.add(departurAirport2);
        departurAirport2.setBounds(390, 190, 150, 27);

        arrivalAirport2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 20)); // NOI18N
        arrivalAirport2.setForeground(new java.awt.Color(255, 255, 255));
        arrivalAirport2.setText("Miami");
        jPanel1.add(arrivalAirport2);
        arrivalAirport2.setBounds(390, 250, 150, 27);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 630, 300);

        jScrollPane1.setBackground(new java.awt.Color(200, 191, 191));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel3.setText("Passenger");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(250, 20, 120, 40);

        jTextField4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(51, 51, 51));
        jTextField4.setText("Enter email adress...");
        jTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField4);
        jTextField4.setBounds(210, 225, 160, 30);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel4.setText("Email");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(50, 230, 50, 25);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel6.setText("Email");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(50, 310, 50, 25);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel7.setText("Email");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(50, 155, 50, 25);

        jTextField5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(51, 51, 51));
        jTextField5.setText("Enter email adress...");
        jTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField5);
        jTextField5.setBounds(210, 305, 160, 30);

        jTextField1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(220, 150, 130, 30);

        jScrollPane1.setViewportView(jPanel2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 300, 630, 480);

        panelMyaccount.setBackground(new java.awt.Color(55, 112, 155));
        panelMyaccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelMyaccount.setLayout(null);

        myAccount.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        myAccount.setForeground(new java.awt.Color(255, 255, 255));
        myAccount.setText("My Account");
        myAccount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myAccount.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelMyaccount.add(myAccount);
        myAccount.setBounds(190, 20, 160, 150);

        personalInfo.setBackground(new java.awt.Color(255, 255, 255));
        personalInfo.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        personalInfo.setText("My Bookings");
        personalInfo.setBorder(null);
        personalInfo.setBorderPainted(false);
        personalInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelMyaccount.add(personalInfo);
        personalInfo.setBounds(140, 300, 230, 40);

        personalInfo1.setBackground(new java.awt.Color(255, 255, 255));
        personalInfo1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        personalInfo1.setText("My Personal Information");
        personalInfo1.setBorder(null);
        personalInfo1.setBorderPainted(false);
        personalInfo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelMyaccount.add(personalInfo1);
        personalInfo1.setBounds(140, 230, 230, 40);

        getContentPane().add(panelMyaccount);
        panelMyaccount.setBounds(0, 0, 530, 460);

        myPersonalInfos.setBackground(new java.awt.Color(55, 112, 155));
        myPersonalInfos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        myPersonalInfos.setLayout(null);

        email.setBackground(new java.awt.Color(255, 255, 255));
        email.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("Email :");
        myPersonalInfos.add(email);
        email.setBounds(80, 110, 70, 30);

        password.setBackground(new java.awt.Color(255, 255, 255));
        password.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password :");
        myPersonalInfos.add(password);
        password.setBounds(80, 160, 100, 30);

        firstName.setBackground(new java.awt.Color(255, 255, 255));
        firstName.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        firstName.setForeground(new java.awt.Color(255, 255, 255));
        firstName.setText("First Name :");
        myPersonalInfos.add(firstName);
        firstName.setBounds(80, 210, 100, 30);

        lastName.setBackground(new java.awt.Color(255, 255, 255));
        lastName.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        lastName.setForeground(new java.awt.Color(255, 255, 255));
        lastName.setText("Last Name :");
        myPersonalInfos.add(lastName);
        lastName.setBounds(80, 260, 100, 30);

        adress.setBackground(new java.awt.Color(255, 255, 255));
        adress.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        adress.setForeground(new java.awt.Color(255, 255, 255));
        adress.setText("Adress :");
        myPersonalInfos.add(adress);
        adress.setBounds(80, 310, 100, 30);

        birthDate.setBackground(new java.awt.Color(255, 255, 255));
        birthDate.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        birthDate.setForeground(new java.awt.Color(255, 255, 255));
        birthDate.setText("Birth date :");
        myPersonalInfos.add(birthDate);
        birthDate.setBounds(80, 360, 100, 30);

        ageCategory.setBackground(new java.awt.Color(255, 255, 255));
        ageCategory.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        ageCategory.setForeground(new java.awt.Color(255, 255, 255));
        ageCategory.setText("Age category");
        myPersonalInfos.add(ageCategory);
        ageCategory.setBounds(270, 460, 110, 30);

        emailField.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        emailField.setForeground(new java.awt.Color(51, 51, 51));
        emailField.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        myPersonalInfos.add(emailField);
        emailField.setBounds(270, 110, 160, 30);

        firstNameField.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        firstNameField.setForeground(new java.awt.Color(51, 51, 51));
        firstNameField.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });
        myPersonalInfos.add(firstNameField);
        firstNameField.setBounds(270, 210, 160, 30);

        lastNameField.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lastNameField.setForeground(new java.awt.Color(51, 51, 51));
        lastNameField.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        lastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFieldActionPerformed(evt);
            }
        });
        myPersonalInfos.add(lastNameField);
        lastNameField.setBounds(270, 260, 160, 30);

        adressField.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        adressField.setForeground(new java.awt.Color(51, 51, 51));
        adressField.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        adressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adressFieldActionPerformed(evt);
            }
        });
        myPersonalInfos.add(adressField);
        adressField.setBounds(270, 310, 160, 30);

        telephoneNulberField.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        telephoneNulberField.setForeground(new java.awt.Color(51, 51, 51));
        telephoneNulberField.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        telephoneNulberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephoneNulberFieldActionPerformed(evt);
            }
        });
        myPersonalInfos.add(telephoneNulberField);
        telephoneNulberField.setBounds(270, 410, 160, 30);
        myPersonalInfos.add(birthDateDate);
        birthDateDate.setBounds(270, 360, 160, 30);

        passwordField.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 10)); // NOI18N
        passwordField.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        passwordField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        myPersonalInfos.add(passwordField);
        passwordField.setBounds(270, 160, 160, 30);

        myPersonalInfo.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        myPersonalInfo.setForeground(new java.awt.Color(255, 255, 255));
        myPersonalInfo.setText("My Personal Information");
        myPersonalInfos.add(myPersonalInfo);
        myPersonalInfo.setBounds(130, 20, 260, 30);

        previous.setBackground(new java.awt.Color(255, 255, 255));
        previous.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 10)); // NOI18N
        previous.setText("Previous");
        previous.setBorder(null);
        previous.setBorderPainted(false);
        previous.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });
        myPersonalInfos.add(previous);
        previous.setBounds(3, 555, 40, 20);

        telephoneNumber.setBackground(new java.awt.Color(255, 255, 255));
        telephoneNumber.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        telephoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        telephoneNumber.setText("Telephone number :");
        myPersonalInfos.add(telephoneNumber);
        telephoneNumber.setBounds(80, 410, 170, 30);

        ageCategory1.setBackground(new java.awt.Color(255, 255, 255));
        ageCategory1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        ageCategory1.setForeground(new java.awt.Color(255, 255, 255));
        ageCategory1.setText("Age category :");
        myPersonalInfos.add(ageCategory1);
        ageCategory1.setBounds(80, 460, 170, 30);

        save1.setBackground(new java.awt.Color(255, 255, 255));
        save1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        save1.setText("Save");
        save1.setBorder(null);
        save1.setBorderPainted(false);
        save1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1ActionPerformed(evt);
            }
        });
        myPersonalInfos.add(save1);
        save1.setBounds(220, 520, 90, 30);

        getContentPane().add(myPersonalInfos);
        myPersonalInfos.setBounds(0, 0, 530, 580);

        myBookingsPanel.setBackground(new java.awt.Color(55, 112, 155));
        myBookingsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        myBookingsPanel.setLayout(null);

        myBookings.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        myBookings.setForeground(new java.awt.Color(255, 255, 255));
        myBookings.setText("My Bookings");
        myBookingsPanel.add(myBookings);
        myBookings.setBounds(200, 10, 140, 40);

        previous1.setBackground(new java.awt.Color(255, 255, 255));
        previous1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 10)); // NOI18N
        previous1.setText("Previous");
        previous1.setBorder(null);
        previous1.setBorderPainted(false);
        previous1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        previous1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previous1ActionPerformed(evt);
            }
        });
        myBookingsPanel.add(previous1);
        previous1.setBounds(3, 555, 40, 20);

        myBookingsTable.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        myBookingsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        myBookingsTable.setToolTipText("");
        myBookingsTable.setSelectionBackground(new java.awt.Color(0, 204, 0));
        myBookingsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        /*
        */
        myBookingsTable.setShowGrid(true);
        bookingScrollPane.setViewportView(myBookingsTable);

        myBookingsPanel.add(bookingScrollPane);
        bookingScrollPane.setBounds(25, 90, 480, 390);

        getBooking.setBackground(new java.awt.Color(255, 255, 255));
        getBooking.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        getBooking.setText("Get Booking tickets");
        getBooking.setBorder(null);
        getBooking.setBorderPainted(false);
        getBooking.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getBookingActionPerformed(evt);
            }
        });
        myBookingsPanel.add(getBooking);
        getBooking.setBounds(170, 520, 190, 30);

        getContentPane().add(myBookingsPanel);
        myBookingsPanel.setBounds(0, 0, 530, 580);

        myTicketsPanel.setBackground(new java.awt.Color(55, 112, 155));
        myTicketsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        myTicketsPanel.setLayout(null);

        myTickets.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        myTickets.setForeground(new java.awt.Color(255, 255, 255));
        myTickets.setText("My Tickets");
        myTicketsPanel.add(myTickets);
        myTickets.setBounds(200, 10, 140, 40);

        previous3.setBackground(new java.awt.Color(255, 255, 255));
        previous3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 10)); // NOI18N
        previous3.setText("Previous");
        previous3.setBorder(null);
        previous3.setBorderPainted(false);
        previous3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        previous3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previous3ActionPerformed(evt);
            }
        });
        myTicketsPanel.add(previous3);
        previous3.setBounds(3, 555, 60, 20);

        myTicketsTable.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        myTicketsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        myTicketsTable.setToolTipText("");
        myTicketsTable.setSelectionBackground(new java.awt.Color(0, 204, 0));
        /*
        myTicketsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        myTicketsTable.setSelectionMode();
        myTicketsTable.setShowGrid(true);
        */
        myTicketsScrollPane.setViewportView(myTicketsTable);

        myTicketsPanel.add(myTicketsScrollPane);
        myTicketsScrollPane.setBounds(25, 90, 480, 390);

        viewTicket.setBackground(new java.awt.Color(255, 255, 255));
        viewTicket.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        viewTicket.setText("View Ticket");
        viewTicket.setBorder(null);
        viewTicket.setBorderPainted(false);
        viewTicket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTicketActionPerformed(evt);
            }
        });
        myTicketsPanel.add(viewTicket);
        viewTicket.setBounds(170, 520, 190, 30);

        getContentPane().add(myTicketsPanel);
        myTicketsPanel.setBounds(0, 0, 530, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void lastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFieldActionPerformed

    private void adressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adressFieldActionPerformed

    private void telephoneNulberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephoneNulberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telephoneNulberFieldActionPerformed

    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_previousActionPerformed

    private void save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_save1ActionPerformed

    private void previous1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previous1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_previous1ActionPerformed

    private void getBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getBookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getBookingActionPerformed

    private void previous3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previous3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_previous3ActionPerformed

    private void viewTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTicketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewTicketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassengerTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassengerTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassengerTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassengerTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassengerTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adress;
    private javax.swing.JTextField adressField;
    private javax.swing.JLabel ageCategory;
    private javax.swing.JLabel ageCategory1;
    private javax.swing.JLabel arrival;
    private javax.swing.JLabel arrival1;
    private javax.swing.JLabel arrivalAirport1;
    private javax.swing.JLabel arrivalAirport2;
    private javax.swing.JLabel arrivalDateTime;
    private javax.swing.JLabel arrivalDateTime1;
    private javax.swing.JLabel birthDate;
    private com.toedter.calendar.JDateChooser birthDateDate;
    private javax.swing.JScrollPane bookingScrollPane;
    private javax.swing.JLabel departurAirport1;
    private javax.swing.JLabel departurAirport2;
    private javax.swing.JLabel departure;
    private javax.swing.JLabel departure1;
    private javax.swing.JLabel departureDateTime;
    private javax.swing.JLabel departureDateTime1;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel firstName;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel from;
    private javax.swing.JLabel from1;
    private javax.swing.JButton getBooking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lastName;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel myAccount;
    private javax.swing.JLabel myBookings;
    private javax.swing.JPanel myBookingsPanel;
    private javax.swing.JTable myBookingsTable;
    private javax.swing.JLabel myPersonalInfo;
    private javax.swing.JPanel myPersonalInfos;
    private javax.swing.JLabel myTickets;
    private javax.swing.JPanel myTicketsPanel;
    private javax.swing.JScrollPane myTicketsScrollPane;
    private javax.swing.JTable myTicketsTable;
    private javax.swing.JPanel panelMyaccount;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton personalInfo;
    private javax.swing.JButton personalInfo1;
    private javax.swing.JButton previous;
    private javax.swing.JButton previous1;
    private javax.swing.JButton previous3;
    private javax.swing.JButton save1;
    private javax.swing.JTextField telephoneNulberField;
    private javax.swing.JLabel telephoneNumber;
    private javax.swing.JLabel to;
    private javax.swing.JLabel to1;
    private javax.swing.JButton viewTicket;
    // End of variables declaration//GEN-END:variables
}
