/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DataAcessObjectImpl.FlightDAOImpl;
import controller.SearchFlightsTableModel;
import java.util.ArrayList;
import model.Flight;

/**
 *
 * @author bibes
 */
public class SearchFlight extends javax.swing.JFrame {

    /**
     * Creates new form SearchFlight
     */
    public SearchFlight() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        textidflight = new javax.swing.JTextField();
        idflight = new javax.swing.JLabel();
        DepartureScrollPane = new javax.swing.JScrollPane();
        searchDeapartureFlights = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        title.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        title.setText("Search Flight:");
        jPanel1.add(title);
        title.setBounds(370, 10, 110, 30);

        search.setText("research");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search);
        search.setBounds(400, 60, 90, 23);

        textidflight.setText("jTextField1");
        textidflight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textidflightActionPerformed(evt);
            }
        });
        jPanel1.add(textidflight);
        textidflight.setBounds(220, 63, 150, 20);

        idflight.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        idflight.setText("Enter the id of a flight: ");
        jPanel1.add(idflight);
        idflight.setBounds(40, 60, 156, 22);

        ArrayList<Flight> flights =  new ArrayList<Flight>();
        flights.add(new FlightDAOImpl().find(5));
        System.out.println(flights.get(0).getIdFlight());
        SearchFlightsTableModel  model = new SearchFlightsTableModel(flights);
        searchDeapartureFlights.setFont(new java.awt.Font("Yu Gothic UI", 0, 12));
        searchDeapartureFlights.setModel(model);
        searchDeapartureFlights.setFocusable(false);
        searchDeapartureFlights.setGridColor(new java.awt.Color(0, 0, 0));
        searchDeapartureFlights.setOpaque(false);
        searchDeapartureFlights.setRowHeight(20);
        searchDeapartureFlights.setSelectionBackground(new java.awt.Color(200, 191, 191));
        searchDeapartureFlights.setShowHorizontalLines(false);
        searchDeapartureFlights.setShowVerticalLines(false);
        searchDeapartureFlights.getTableHeader().setReorderingAllowed(false);
        DepartureScrollPane.setViewportView(searchDeapartureFlights);

        jPanel1.add(DepartureScrollPane);
        DepartureScrollPane.setBounds(210, 140, 452, 402);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void textidflightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textidflightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textidflightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchFlight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane DepartureScrollPane;
    private javax.swing.JLabel idflight;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton search;
    private javax.swing.JTable searchDeapartureFlights;
    private javax.swing.JTextField textidflight;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
