/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author bibes
 */
public class SearchDeleteCoupon extends javax.swing.JFrame {

    /**
     * Creates new form SearchDeleteCoupon
     */
    public SearchDeleteCoupon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        title3 = new javax.swing.JLabel();
        idflight3 = new javax.swing.JLabel();
        textidflight3 = new javax.swing.JTextField();
        search3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel8.setLayout(null);

        title3.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        title3.setText("Search Coupons:");
        jPanel8.add(title3);
        title3.setBounds(380, 10, 150, 30);

        idflight3.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        idflight3.setText("Enter the id of the booking: ");
        jPanel8.add(idflight3);
        idflight3.setBounds(30, 60, 200, 22);

        textidflight3.setText("jTextField1");
        textidflight3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textidflight3ActionPerformed(evt);
            }
        });
        jPanel8.add(textidflight3);
        textidflight3.setBounds(230, 63, 150, 20);

        search3.setText("research");
        search3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search3ActionPerformed(evt);
            }
        });
        jPanel8.add(search3);
        search3.setBounds(400, 60, 90, 23);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        jPanel8.add(jScrollPane4);
        jScrollPane4.setBounds(140, 160, 630, 330);

        jButton3.setText("Delete");
        jPanel8.add(jButton3);
        jButton3.setBounds(840, 420, 73, 23);

        jLabel1.setText("rajouter addd");
        jPanel8.add(jLabel1);
        jLabel1.setBounds(830, 200, 100, 50);

        getContentPane().add(jPanel8);
        jPanel8.setBounds(0, 0, 950, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textidflight3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textidflight3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textidflight3ActionPerformed

    private void search3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchDeleteCoupon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchDeleteCoupon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchDeleteCoupon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchDeleteCoupon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchDeleteCoupon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idflight3;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton search3;
    private javax.swing.JTextField textidflight3;
    private javax.swing.JLabel title3;
    // End of variables declaration//GEN-END:variables
}
