/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author bibes
 */
public class UpdateDeleteBooking extends javax.swing.JFrame {

    /**
     * Creates new form UpdateDeleteBooking
     */
    public UpdateDeleteBooking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        textidflight1 = new javax.swing.JTextField();
        search1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        nameflight1 = new javax.swing.JLabel();
        deparrturedate2 = new javax.swing.JLabel();
        airplane2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableseat1 = new javax.swing.JTable();
        update1 = new javax.swing.JButton();
        delete1 = new javax.swing.JButton();
        deleteseat2 = new javax.swing.JButton();
        choicedeparturedate2 = new com.toedter.calendar.JDateChooser();
        choicearrivalairport2 = new javax.swing.JComboBox();
        choiceairplane2 = new javax.swing.JComboBox();
        choiceclass = new javax.swing.JLabel();
        priceofaseat2 = new javax.swing.JTextField();
        priceofaseat3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        title1 = new javax.swing.JLabel();
        idflight1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel5.setLayout(null);

        textidflight1.setText("jTextField1");
        textidflight1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textidflight1ActionPerformed(evt);
            }
        });
        jPanel5.add(textidflight1);
        textidflight1.setBounds(230, 63, 150, 20);

        search1.setText("research");
        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1ActionPerformed(evt);
            }
        });
        jPanel5.add(search1);
        search1.setBounds(400, 60, 90, 23);

        jPanel6.setBackground(new java.awt.Color(240, 240, 0));
        jPanel6.setLayout(null);

        nameflight1.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        nameflight1.setText("Choose the flight:");
        jPanel6.add(nameflight1);
        nameflight1.setBounds(40, 30, 140, 22);

        deparrturedate2.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        deparrturedate2.setText("Date of the booking:");
        jPanel6.add(deparrturedate2);
        deparrturedate2.setBounds(40, 70, 150, 22);

        airplane2.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        airplane2.setText("Number of tickets:");
        jPanel6.add(airplane2);
        airplane2.setBounds(40, 110, 140, 22);

        tableseat1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane2.setViewportView(tableseat1);

        jPanel6.add(jScrollPane2);
        jScrollPane2.setBounds(330, 30, 440, 180);

        update1.setText("update");
        jPanel6.add(update1);
        update1.setBounds(410, 230, 67, 23);

        delete1.setText("Delete");
        jPanel6.add(delete1);
        delete1.setBounds(610, 230, 63, 23);

        deleteseat2.setText("delete seat");
        jPanel6.add(deleteseat2);
        deleteseat2.setBounds(790, 110, 90, 23);
        jPanel6.add(choicedeparturedate2);
        choicedeparturedate2.setBounds(190, 70, 120, 20);

        choicearrivalairport2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel6.add(choicearrivalairport2);
        choicearrivalairport2.setBounds(190, 110, 120, 20);

        choiceairplane2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel6.add(choiceairplane2);
        choiceairplane2.setBounds(190, 30, 120, 20);

        choiceclass.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        choiceclass.setText("Class name:");
        jPanel6.add(choiceclass);
        choiceclass.setBounds(40, 150, 140, 30);

        priceofaseat2.setText("jTextField1");
        jPanel6.add(priceofaseat2);
        priceofaseat2.setBounds(190, 190, 120, 20);

        priceofaseat3.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        priceofaseat3.setText("Price of a seat:");
        jPanel6.add(priceofaseat3);
        priceofaseat3.setBounds(40, 190, 110, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBox1);
        jComboBox1.setBounds(190, 150, 120, 20);

        jPanel5.add(jPanel6);
        jPanel6.setBounds(30, 110, 920, 280);

        title1.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        title1.setText("Search booking:");
        jPanel5.add(title1);
        title1.setBounds(370, 10, 150, 30);

        idflight1.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        idflight1.setText("Enter the id of the booking: ");
        jPanel5.add(idflight1);
        idflight1.setBounds(30, 60, 200, 22);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 920, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textidflight1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textidflight1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textidflight1ActionPerformed

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateDeleteBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel airplane2;
    private javax.swing.JComboBox choiceairplane2;
    private javax.swing.JComboBox choicearrivalairport2;
    private javax.swing.JLabel choiceclass;
    private com.toedter.calendar.JDateChooser choicedeparturedate2;
    private javax.swing.JButton delete1;
    private javax.swing.JButton deleteseat2;
    private javax.swing.JLabel deparrturedate2;
    private javax.swing.JLabel idflight1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nameflight1;
    private javax.swing.JTextField priceofaseat2;
    private javax.swing.JLabel priceofaseat3;
    private javax.swing.JButton search1;
    private javax.swing.JTable tableseat1;
    private javax.swing.JTextField textidflight1;
    private javax.swing.JLabel title1;
    private javax.swing.JButton update1;
    // End of variables declaration//GEN-END:variables
}
