/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.util.ArrayList;
import model.*;
/**
 *
 * @author Unknow
 */
public class WorldAirlineCustomerProgramTest extends javax.swing.JFrame {

    /**
     * Creates new form WorldAirlineCustomerProgramTest
     */
    
    public WorldAirlineCustomerProgramTest() {
        initComponents();
        this.setSize(1920,1080);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        oneWay = new javax.swing.JRadioButton();
        economyClass = new javax.swing.JRadioButton();
        toArrival = new javax.swing.JComboBox<>();
        to = new javax.swing.JLabel();
        seat = new javax.swing.JLabel();
        fromDeparture = new javax.swing.JComboBox<>();
        from = new javax.swing.JLabel();
        arrivalDate = new com.toedter.calendar.JDateChooser();
        departure = new javax.swing.JLabel();
        departureCalendar = new com.toedter.calendar.JDateChooser();
        roundTrip = new javax.swing.JRadioButton();
        businessClass = new javax.swing.JRadioButton();
        firstClass = new javax.swing.JRadioButton();
        arrival = new javax.swing.JLabel();
        arrival1 = new javax.swing.JLabel();
        toArrival1 = new javax.swing.JComboBox<>();
        search1 = new javax.swing.JButton();
        worldWride = new javax.swing.JLabel();
        DeparturePanel = new javax.swing.JPanel();
        Next = new javax.swing.JButton();
        DepartureScrollPane = new javax.swing.JScrollPane();
        searchDeapartureFlights = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(200, 191, 191));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        buttonGroup1.add(oneWay);
        oneWay.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        oneWay.setForeground(new java.awt.Color(255, 255, 255));
        oneWay.setText("ONE-WAY");
        oneWay.setContentAreaFilled(false);
        oneWay.setFocusable(false);
        oneWay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneWayActionPerformed(evt);
            }
        });
        jPanel1.add(oneWay);
        oneWay.setBounds(190, 20, 110, 30);

        buttonGroup2.add(economyClass);
        economyClass.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        economyClass.setForeground(new java.awt.Color(255, 255, 255));
        economyClass.setText("Economy Class");
        economyClass.setContentAreaFilled(false);
        economyClass.setFocusable(false);
        economyClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                economyClassActionPerformed(evt);
            }
        });
        jPanel1.add(economyClass);
        economyClass.setBounds(130, 380, 120, 30);

        toArrival.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        toArrival.setOpaque(false);
        toArrival.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toArrivalActionPerformed(evt);
            }
        });
        jPanel1.add(toArrival);
        toArrival.setBounds(130, 270, 110, 20);

        to.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        to.setIcon(new javax.swing.ImageIcon("D:\\GITHUB\\worldAirline\\img\\location.png")); // NOI18N
        to.setText("To");
        jPanel1.add(to);
        to.setBounds(30, 120, 70, 40);

        seat.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        seat.setIcon(new javax.swing.ImageIcon("D:\\GITHUB\\worldAirline\\img\\seat.png")); // NOI18N
        seat.setText("Seat");
        jPanel1.add(seat);
        seat.setBounds(30, 340, 80, 40);

        fromDeparture.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fromDeparture.setOpaque(false);
        jPanel1.add(fromDeparture);
        fromDeparture.setBounds(130, 80, 110, 20);

        from.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        from.setIcon(new javax.swing.ImageIcon("D:\\GITHUB\\worldAirline\\img\\location.png")); // NOI18N
        from.setText("From");
        jPanel1.add(from);
        from.setBounds(30, 70, 70, 40);
        jPanel1.add(arrivalDate);
        arrivalDate.setBounds(130, 220, 110, 20);

        departure.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        departure.setIcon(new javax.swing.ImageIcon("D:\\GITHUB\\worldAirline\\img\\calendar.png")); // NOI18N
        departure.setText("Departure");
        jPanel1.add(departure);
        departure.setBounds(30, 170, 80, 40);
        jPanel1.add(departureCalendar);
        departureCalendar.setBounds(130, 180, 110, 20);

        buttonGroup1.add(roundTrip);
        roundTrip.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        roundTrip.setForeground(new java.awt.Color(255, 255, 255));
        roundTrip.setText("ROUND TRIP");
        roundTrip.setContentAreaFilled(false);
        roundTrip.setFocusable(false);
        roundTrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundTripActionPerformed(evt);
            }
        });
        jPanel1.add(roundTrip);
        roundTrip.setBounds(30, 20, 110, 30);

        buttonGroup2.add(businessClass);
        businessClass.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        businessClass.setForeground(new java.awt.Color(255, 255, 255));
        businessClass.setText("Business Class");
        businessClass.setContentAreaFilled(false);
        businessClass.setFocusable(false);
        businessClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                businessClassActionPerformed(evt);
            }
        });
        jPanel1.add(businessClass);
        businessClass.setBounds(130, 350, 110, 30);

        buttonGroup2.add(firstClass);
        firstClass.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        firstClass.setForeground(new java.awt.Color(255, 255, 255));
        firstClass.setText("First Class");
        firstClass.setContentAreaFilled(false);
        firstClass.setFocusable(false);
        firstClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstClassActionPerformed(evt);
            }
        });
        jPanel1.add(firstClass);
        firstClass.setBounds(130, 320, 110, 30);

        arrival.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        arrival.setIcon(new javax.swing.ImageIcon("D:\\GITHUB\\worldAirline\\img\\users.png")); // NOI18N
        arrival.setText("Passenger(s)");
        jPanel1.add(arrival);
        arrival.setBounds(30, 260, 90, 40);

        arrival1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        arrival1.setIcon(new javax.swing.ImageIcon("D:\\GITHUB\\worldAirline\\img\\calendar.png")); // NOI18N
        arrival1.setText("Arrival");
        jPanel1.add(arrival1);
        arrival1.setBounds(30, 210, 80, 40);

        toArrival1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        toArrival1.setOpaque(false);
        toArrival1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toArrival1ActionPerformed(evt);
            }
        });
        jPanel1.add(toArrival1);
        toArrival1.setBounds(130, 130, 110, 20);

        search1.setBackground(new java.awt.Color(102, 102, 102));
        search1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        search1.setForeground(new java.awt.Color(255, 255, 255));
        search1.setText("Search");
        search1.setBorderPainted(false);
        search1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        search1.setFocusable(false);
        jPanel1.add(search1);
        search1.setBounds(130, 440, 110, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 230, 360, 500);

        worldWride.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 110)); // NOI18N
        worldWride.setText("WorldAirline");
        getContentPane().add(worldWride);
        worldWride.setBounds(430, 0, 580, 110);

        DeparturePanel.setOpaque(false);
        DeparturePanel.setLayout(null);

        Next.setBackground(new java.awt.Color(102, 102, 102));
        Next.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        Next.setForeground(new java.awt.Color(255, 255, 255));
        Next.setText("Next");
        Next.setBorderPainted(false);
        Next.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Next.setFocusable(false);
        DeparturePanel.add(Next);
        Next.setBounds(710, 560, 110, 30);

        searchDeapartureFlights.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        searchDeapartureFlights.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"WordlAirline", "1", "PARIS", "10/05/2021 at 8:30 AM", "MIAMI", "11/05/2021 at 04:56 PM"},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Airline", "Flight Number", "From", "Departure", "To", "Arrival"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        searchDeapartureFlights.setFocusable(false);
        searchDeapartureFlights.setGridColor(new java.awt.Color(0, 0, 0));
        searchDeapartureFlights.setOpaque(false);
        searchDeapartureFlights.setRowHeight(20);
        searchDeapartureFlights.setSelectionBackground(new java.awt.Color(200, 191, 191));
        searchDeapartureFlights.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        searchDeapartureFlights.setShowHorizontalLines(false);
        searchDeapartureFlights.setShowVerticalLines(false);
        searchDeapartureFlights.getTableHeader().setReorderingAllowed(false);
        DepartureScrollPane.setViewportView(searchDeapartureFlights);

        DeparturePanel.add(DepartureScrollPane);
        DepartureScrollPane.setBounds(0, 40, 860, 500);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Departure>>");
        DeparturePanel.add(jLabel1);
        jLabel1.setBounds(0, 0, 150, 30);

        getContentPane().add(DeparturePanel);
        DeparturePanel.setBounds(510, 190, 820, 590);

        backGround.setIcon(new javax.swing.ImageIcon("D:\\GITHUB\\worldAirline\\img\\planeProgram.jpg")); // NOI18N
        getContentPane().add(backGround);
        backGround.setBounds(0, -50, 1920, 1380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oneWayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneWayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneWayActionPerformed

    private void economyClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_economyClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_economyClassActionPerformed

    private void roundTripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundTripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roundTripActionPerformed

    private void businessClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_businessClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_businessClassActionPerformed

    private void firstClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstClassActionPerformed

    private void toArrivalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toArrivalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toArrivalActionPerformed

    private void toArrival1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toArrival1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toArrival1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorldAirlineCustomerProgramTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorldAirlineCustomerProgramTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorldAirlineCustomerProgramTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorldAirlineCustomerProgramTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorldAirlineCustomerProgramTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DeparturePanel;
    private javax.swing.JScrollPane DepartureScrollPane;
    private javax.swing.JButton Next;
    private javax.swing.JLabel arrival;
    private javax.swing.JLabel arrival1;
    private com.toedter.calendar.JDateChooser arrivalDate;
    private javax.swing.JLabel backGround;
    private javax.swing.JRadioButton businessClass;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel departure;
    private com.toedter.calendar.JDateChooser departureCalendar;
    private javax.swing.JRadioButton economyClass;
    private javax.swing.JRadioButton firstClass;
    private javax.swing.JLabel from;
    private javax.swing.JComboBox<String> fromDeparture;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton oneWay;
    private javax.swing.JRadioButton roundTrip;
    private javax.swing.JButton search1;
    private javax.swing.JTable searchDeapartureFlights;
    private javax.swing.JLabel seat;
    private javax.swing.JLabel to;
    private javax.swing.JComboBox<String> toArrival;
    private javax.swing.JComboBox<String> toArrival1;
    private javax.swing.JLabel worldWride;
    // End of variables declaration//GEN-END:variables
}
